import Foundation

// Beginner-level explanations for Units 4–6.

extension Curriculum {
    static let explanationsCore: [String: [ExplanationSection]] = [

        // MARK: Unit 4 · Comparing groups

        "t-tests": [
            idea("Is the difference between two means bigger than noise?",
                 "A **t-test** compares means. It asks whether a difference is large **relative to how much the means would vary by chance**. The heart of every t-test is a simple ratio: t = (difference in means) / (standard error of that difference). A t near 0 means the difference is small compared with the noise; a t of 3 or more means the difference is several standard errors away from zero.",
                 "There are three versions, and choosing the right one depends on the **design**. A **one-sample** t-test compares one group's mean with a fixed number (e.g. is accuracy above the 50% chance level?). An **independent-samples** t-test compares two separate groups of people. A **paired** t-test compares the same people measured twice (before vs. after) — it works by computing each person's difference and testing whether the average difference is zero.",
                 "Pairing is powerful: people differ a lot from each other, but each person is compared only with themselves, so those individual differences drop out of the noise.",
                 "For independent groups, use **Welch's t-test** by default. It doesn't assume the two groups have equal variances and loses almost nothing when they do."),
            analogy("Comparing runners",
                    "To see whether new shoes make people faster, you could time one group in old shoes and a different group in new shoes (independent). Or you could time the **same** runners in both (paired). The paired design is far more sensitive: a fast runner stays fast in both pairs of shoes, so what's left to compare is purely the effect of the shoes."),
            worked("A paired t-test by hand",
                   "Five students' scores before and after a workshop: (60, 64), (72, 75), (55, 61), (80, 82), (66, 70).",
                   "Differences: 4, 3, 6, 2, 4. Mean difference = 19 / 5 = **3.8**.",
                   "SD of the differences ≈ **1.48**; SE = 1.48 / √5 ≈ **0.66**.",
                   "t = 3.8 / 0.66 ≈ **5.7** with 4 degrees of freedom, p ≈ .005. Even with five people the improvement is clear, because every student improved by a similar amount."),
            inWords("Reporting a t-test",
                    "Paired: “Scores increased after the workshop (*M*_diff = 3.8, 95% CI [1.9, 5.7]), *t*(4) = 5.72, *p* = .005, *d*_z = 2.6.” Independent (Welch): “Active-learning students scored higher than lecture students, *t*(96.4) = 2.41, *p* = .018, *d* = 0.48.”"),
        ],

        "anova": [
            idea("Comparing three or more groups at once",
                 "With three or more groups you could run a t-test for every pair, but each test is another chance for a false positive. **ANOVA** (analysis of variance) asks one question first: **is there any difference among the group means at all?**",
                 "ANOVA works by splitting the variability in the data into two parts. **Between-group variability** is how much the group means differ from the overall mean. **Within-group variability** is how much individuals differ from their own group's mean — the noise. The **F ratio** divides the first by the second. If the groups don't really differ, F should be around 1; a large F means the group means are more spread out than noise alone would produce.",
                 "A significant F tells you that **some** groups differ, not which ones. Follow up with **post-hoc comparisons** that correct for multiple testing (such as Tukey's HSD) or with **planned contrasts** you specified in advance.",
                 "**Factorial ANOVA** handles two or more factors at once (e.g. sentence structure × distance). It estimates a **main effect** for each factor and an **interaction** — whether the effect of one factor depends on the level of the other."),
            analogy("Voices in a crowded room",
                    "Imagine three people talking in a noisy room. Between-group variability is how different their voices are from each other; within-group variability is the background chatter. If the voices are clearly distinct compared with the chatter (a large F), you can tell the speakers apart. If they're no more different than the chatter itself, you can't."),
            worked("F from a tiny example",
                   "Three groups of three scores each: A = 2, 3, 4 (mean 3); B = 4, 5, 6 (mean 5); C = 6, 7, 8 (mean 7). Grand mean = 5.",
                   "**Between**: each group mean's squared distance from 5, times 3 people: 3 × [(3−5)² + (5−5)² + (7−5)²] = 3 × 8 = 24, on 2 df → mean square = **12**.",
                   "**Within**: every score's squared distance from its own group mean: in each group (−1)² + 0² + 1² = 2, total 6, on 6 df → mean square = **1**.",
                   "F = 12 / 1 = **12** with (2, 6) df, p ≈ .008. The groups differ much more than the scores within them do."),
            inWords("Reporting an ANOVA",
                    "“Teaching method affected post-test scores, *F*(2, 147) = 5.12, *p* = .007, η²ₚ = .07. Tukey-corrected comparisons showed that active learning outperformed lecture (*p* = .005); other differences were not significant.”"),
        ],

        "ancova": [
            idea("Comparing groups after accounting for where people started",
                 "In many experiments you measure people **before** the treatment too: a pre-test. Students who start high tend to finish high, regardless of which teaching method they get. That starting-point variation is noise that makes the method effect harder to see.",
                 "**ANCOVA** (analysis of covariance) compares the groups on the outcome while **adjusting for** the pre-test. Conceptually, it asks: for two students who had the **same** pre-test score, how different would we expect their post-test scores to be if one got active learning and the other got lecture?",
                 "Under the hood, ANCOVA is just a regression: post-test ~ group + pre-test. The group coefficients are **adjusted mean differences**. Because randomization already balanced the groups on average, the covariate doesn't fix bias — it **reduces noise**, which increases power, often dramatically.",
                 "**Contrast coding** decides what each group coefficient compares. With the default **treatment coding**, each group is compared with a **reference** group (e.g. lecture). With **sum coding**, each group is compared with the **grand mean** of all groups. The model fit is identical; only the question each number answers changes."),
            analogy("A handicap in golf",
                    "Golf uses handicaps so that players of different skill can be compared fairly: a score is judged relative to what that player usually shoots. ANCOVA does something similar — it judges each student's post-test relative to what you'd expect from their pre-test, then compares methods on that fairer basis."),
            worked("Why adjustment helps",
                   "Two methods each have 50 students. Post-test scores have an SD of 10, and the pre-test correlates r = .7 with the post-test.",
                   "Without the covariate, the noise in the comparison is based on SD = 10.",
                   "With it, the remaining (residual) SD is 10 × √(1 − .7²) = 10 × 0.71 ≈ **7.1**.",
                   "A 4-point difference is d = 0.4 against SD 10, but effectively 4 / 7.1 ≈ **0.56** after adjustment — which is why ANCOVA needs roughly half the sample of a post-only comparison."),
            inWords("Reporting an ANCOVA",
                    "“Controlling for pre-test scores, active learning produced higher post-test scores than lecture, *b* = 4.6, 95% CI [1.9, 7.3], *t*(144) = 3.36, *p* = .001; flipped classrooms did not differ from lecture, *b* = 0.9, *p* = .51.”"),
        ],

        "chi-square": [
            idea("Are two categorical variables related?",
                 "When both variables are categories — region and vote choice, social class and university attendance, speaker group and which variant they use — you summarize the data in a **contingency table** of counts. The question is whether the pattern of counts differs from what you'd expect **if the two variables were unrelated**.",
                 "The chi-square (χ²) test makes that comparison cell by cell. For each cell, the **expected count** under independence is (row total × column total) / grand total. Then χ² adds up (observed − expected)² / expected over all cells. Big gaps between observed and expected counts make χ² large.",
                 "The degrees of freedom are (rows − 1) × (columns − 1), and the p-value comes from the chi-square distribution. Because χ² grows with sample size, also report an effect size such as **Cramér's V** (0 = no association, 1 = perfect).",
                 "Two conditions matter: each person must count **once** in the table (independence), and expected counts should be at least about **5** per cell; otherwise use Fisher's exact test."),
            analogy("A seating chart",
                    "At a mixed party, if guests ignore which department people work in, each table should have roughly the same mix of departments as the whole party. If one table is full of engineers and another of teachers, the seating isn't independent of department. χ² measures how far the actual seating departs from the “random mixing” expectation."),
            worked("Expected counts",
                   "100 students: 50 working-class, 50 middle-class; 40 attended university overall.",
                   "If attendance were independent of class, each group would have 40% attending: expected **20** attending and **30** not, in each group.",
                   "Observed: working-class 12 attended / 38 didn't; middle-class 28 / 22.",
                   "χ² = (12−20)²/20 + (38−30)²/30 + (28−20)²/20 + (22−30)²/30 = 3.2 + 2.13 + 3.2 + 2.13 = **10.7**, with 1 df, p ≈ .001."),
            inWords("Reporting a chi-square test",
                    "“University attendance differed by class background, χ²(1, *N* = 100) = 10.67, *p* = .001, *V* = .33: 24% of working-class students attended, compared with 56% of middle-class students.” Always give the percentages, not just the statistic."),
        ],

        "non-parametric": [
            idea("Tests that use ranks instead of raw values",
                 "Classic tests such as the t-test assume roughly normal data (or large samples) and treat the numbers as having equal spacing. When those assumptions are doubtful — a single ordinal rating, a tiny skewed sample, extreme outliers — **rank-based (non-parametric) tests** are a useful alternative.",
                 "They replace each value with its **rank** (1st smallest, 2nd smallest, …) and analyze the ranks. Because a rank only records order, an outlier of 10,000 is just “the largest” — it can't drag the result around.",
                 "Each common test has a rank-based partner: **Mann–Whitney U** for two independent groups, **Wilcoxon signed-rank** for paired data, **Kruskal–Wallis** for three or more groups, and **Spearman's ρ** for correlation.",
                 "They answer a slightly different question: not “are the means different?” but roughly “do values in one group **tend to be larger** than in the other?”"),
            analogy("A race with no stopwatch",
                    "If you only know the order in which runners crossed the finish line, you can still tell which team tends to finish ahead — even without anyone's actual time. Rank tests work the same way: they use only the order of the values."),
            worked("Ranks tame an outlier",
                   "Group A: 3, 4, 5. Group B: 6, 7, 100.",
                   "Means: A = 4, B ≈ 37.7 — the 100 dominates B's mean and inflates its variance.",
                   "Ranks of all six values: 3→1, 4→2, 5→3, 6→4, 7→5, 100→6. Group A's ranks sum to 6, group B's to 15.",
                   "Every B value outranks every A value — the strongest possible separation for these sizes — and the 100 counts only as “rank 6,” no differently than 8 would."),
            inWords("Reporting a rank test",
                    "“Because the item was ordinal, groups were compared with a Mann–Whitney test: rural respondents did not differ from urban respondents, *U* = 9,820, *p* = .41.” Report medians alongside the test."),
        ],

        // MARK: Unit 5 · Relationships

        "correlation": [
            idea("How strongly do two variables move together?",
                 "A **correlation coefficient (r)** summarizes how closely two numerical variables follow a straight-line relationship. It ranges from **−1** (a perfect downward line) through **0** (no linear relationship) to **+1** (a perfect upward line).",
                 "The **sign** gives the direction: positive means high values of one go with high values of the other; negative means high goes with low. The **size** gives the strength: around .1 is small, .3 moderate, and .5 or more large in much of social science (though these are only rough guides).",
                 "**r²** is the proportion of variance the two variables share: r = .5 means 25% shared variance.",
                 "Three warnings. First, r only detects **straight-line** relationships — a strong curve can give r ≈ 0. Second, a single **outlier** can create or hide a correlation. Third, **correlation isn't causation**: two variables can move together because a third variable drives both. Always look at the scatterplot."),
            analogy("Dancing partners",
                    "Think of two dancers. If one steps forward whenever the other does, they're positively correlated; if one steps back whenever the other steps forward, they're negatively correlated; if they move independently, r is near 0. A correlation of +1 is perfectly synchronized dancing; +0.5 is a pair who mostly follow each other but often improvise."),
            worked("Computing r with z-scores",
                   "Four people's (study hours, exam score): (1, 50), (2, 60), (3, 65), (4, 85).",
                   "Convert each variable to z-scores. Hours (mean 2.5, SD 1.29): −1.16, −0.39, 0.39, 1.16. Scores (mean 65, SD 14.7): −1.02, −0.34, 0, 1.36.",
                   "Multiply each pair: 1.18, 0.13, 0, 1.58. Sum = 2.89.",
                   "Divide by n − 1 = 3: r ≈ **0.96** — a very strong positive relationship. People above average on one tend to be above average on the other."),
            inWords("Reporting a correlation",
                    "“Rumination was positively correlated with anxiety, *r*(373) = .52, 95% CI [.44, .59], *p* < .001.” The number in parentheses is the degrees of freedom, n − 2."),
        ],

        "between-within": [
            idea("When people are measured many times, there are two relationships",
                 "In a daily diary study, each person reports how many hours they worked and how they felt, every day for two weeks. You might ask “is working more related to wellbeing?” — but that question splits in two.",
                 "The **between-person** question compares **people**: do people who *usually* work long hours have different *average* wellbeing from people who usually work short hours? Each person contributes one data point — their average.",
                 "The **within-person** question compares **days within the same person**: on days when someone works *more than they usually do*, do they feel better or worse *than they usually do*? Each person is compared only with themselves.",
                 "These can have **opposite signs**. Perhaps people who choose demanding jobs are more satisfied overall (positive between), yet everyone feels worse on their own extra-long days (negative within). Pooling all the days into one correlation blends the two and answers neither — and treats 1,400 days as if they were 1,400 independent people.",
                 "The fix is to **separate the components**: compute each person's mean (between) and each day's deviation from that person's own mean (within, called **person-mean centering**), then analyze them separately or together in a multilevel model."),
            analogy("Coffee and alertness",
                    "Across people, heavy coffee drinkers might be *more* tired on average — perhaps they drink coffee *because* they sleep badly (negative between). But within any one person, the days they drink an extra cup are the days they feel more alert (positive within). Concluding “coffee makes you tired” from the between-person pattern would be the **ecological fallacy**: assuming a group-level pattern holds inside each individual."),
            worked("Splitting one day into two parts",
                   "Maya usually works 8 hours (her 14-day average). On Tuesday she worked 10.",
                   "Her **between-person** value is 8 — the same on every one of her days. It's compared with other people's averages.",
                   "Her **within-person** value for Tuesday is 10 − 8 = **+2**: two hours more than her usual. If the within-person slope is −0.25, Tuesday's wellbeing is predicted to be 0.25 × 2 = **0.5 points below her usual level**.",
                   "Sam usually works 6 hours and also worked 8 on one day: within value +2 as well. The within-person slope treats Maya's +2 and Sam's +2 the same, even though their raw hours (10 vs. 8) differ."),
            inWords("Reporting both components",
                    "“At the between-person level, people who typically worked longer reported higher average wellbeing (*b* = 0.30, *p* < .001). Within persons, days with more work than usual were associated with lower wellbeing (*b* = −0.25, *p* < .001).”"),
        ],

        "simple-regression": [
            idea("Drawing the best straight line through the data",
                 "Correlation tells you how strong a linear relationship is. **Regression** goes further: it describes the line itself, so you can make predictions and say how much the outcome changes per unit of the predictor.",
                 "The line has two numbers. The **intercept (b₀)** is the predicted outcome when the predictor is 0. The **slope (b₁)** is how much the predicted outcome changes for a **one-unit increase** in the predictor. The prediction for anyone is ŷ = b₀ + b₁ × x.",
                 "For each person, the **residual** is the gap between their actual value and the line's prediction (observed − predicted). **Least squares** chooses the line that makes the sum of squared residuals as small as possible — the line that fits the data best overall.",
                 "**R²** tells you what share of the variation in the outcome the line explains. A slope can be significant while R² is small: the predictor matters, but many other things do too.",
                 "Before trusting the results, check four conditions (**LINE**): a **L**inear pattern, **I**ndependent observations, **N**early normal residuals, and **E**qual (constant) spread of residuals across the range of the predictor. A residual plot is the main tool."),
            analogy("A trend line on a growth chart",
                    "A pediatrician's chart shows how height tends to increase with age. Any individual child is above or below the line (their residual), but the line summarizes the typical relationship and lets you predict an expected height at a given age. Regression is how that line is drawn from data."),
            worked("Using a fitted line",
                   "A regression of anxiety on rumination gives ŷ = 1.6 + 0.48 × rumination.",
                   "Intercept 1.6: predicted anxiety for someone with rumination 0 (outside the 1–7 scale, so not meaningful by itself).",
                   "Slope 0.48: each extra point of rumination predicts **0.48** more points of anxiety.",
                   "Someone with rumination 5 is predicted to have 1.6 + 0.48 × 5 = **4.0**. If their actual anxiety is 4.6, their residual is 4.6 − 4.0 = **+0.6**: they're more anxious than the line predicts."),
            inWords("Reporting a regression",
                    "“Rumination predicted anxiety, *b* = 0.48, 95% CI [0.40, 0.56], *t*(373) = 11.8, *p* < .001, *R*² = .27: each one-point increase in rumination was associated with about half a point more anxiety.”"),
        ],

        "multiple-regression": [
            idea("Several predictors at once — and “holding constant”",
                 "Real outcomes have many causes. **Multiple regression** includes several predictors in one model: ŷ = b₀ + b₁x₁ + b₂x₂ + …. Each coefficient now means something more specific: the change in the outcome for a one-unit change in **that** predictor, **holding the other predictors constant**.",
                 "“Holding constant” is the key idea. If rumination and social media use both predict anxiety, and they're correlated with each other, the multiple-regression coefficient for social media tells you its association with anxiety **among people with the same level of rumination**. That can be much smaller than its simple correlation with anxiety.",
                 "**Categorical predictors** enter as **dummy variables**: a predictor with k categories becomes k − 1 columns of 0s and 1s, each compared with a **reference** category. **Interactions** (x₁ × x₂) let the effect of one predictor depend on the value of another.",
                 "Add predictors for substantive reasons, not by trial and error. Automated **stepwise** selection tends to find patterns that are just noise and don't replicate."),
            analogy("Comparing houses",
                    "Bigger houses sell for more — but bigger houses also tend to have more bathrooms. A multiple regression of price on size **and** bathrooms answers: “For two houses with the same number of bathrooms, how much more does an extra square meter add?” That's the size effect with bathrooms held constant."),
            worked("Why coefficients change when you add predictors",
                   "Alone, social media use predicts anxiety with b = 0.40.",
                   "But heavy social media users also ruminate more, and rumination strongly predicts anxiety.",
                   "Add rumination to the model: the social media coefficient drops to b = **0.14**. Most of its original association ran **through** (or alongside) rumination; 0.14 is what's left among people with equal rumination.",
                   "Neither number is “wrong” — they answer different questions. Always say what was held constant."),
            inWords("Reporting multiple regression",
                    "“Controlling for rumination, age, and region, social media use remained a small positive predictor of anxiety, *b* = 0.14, 95% CI [0.04, 0.24], *p* = .006. The model explained 31% of the variance, adjusted *R*² = .30.”"),
        ],

        "comparing-predictors": [
            idea("Which predictor matters more?",
                 "When two predictors are related — social media use and phone checking, say — researchers often want to know which one has the stronger link to an outcome. Raw coefficients can't answer that if the predictors are measured on different scales.",
                 "**Standardized coefficients (β)** put everything in SD units: β is how many SDs the outcome changes per SD of the predictor, holding the others constant. Now the numbers are comparable.",
                 "**Unique variance (ΔR²)** asks a different question: how much extra variance does a predictor explain **after** the others are already in the model? Some variance is **shared** — explained by either predictor — and can't be credited to either one alone.",
                 "**Multicollinearity** is when predictors are so strongly correlated that the model can't tell their effects apart. The **variance inflation factor (VIF)** measures it: 1 means no overlap; values above about 5–10 mean individual coefficients become unstable."),
            analogy("Two people carrying a couch",
                    "If two friends carry a couch together, you can see how much lifting each does only if they sometimes carry it separately. If they always lift at exactly the same time, you can't tell who's doing the work — that's multicollinearity. The total (R²) is clear; the split between them isn't."),
            worked("Shared and unique variance",
                   "Social media alone explains R² = .20 of rumination. Phone checking alone explains .12. Together they explain .23.",
                   "Unique to social media = .23 − .12 = **.11**. Unique to phone checking = .23 − .20 = **.03**.",
                   "Shared = .23 − .11 − .03 = **.09** — explained by either predictor, but not attributable to one.",
                   "Social media has more unique variance, consistent with a larger β."),
            inWords("Reporting a comparison",
                    "“Social media use (β = .35) was a stronger unique predictor of rumination than phone checking (β = .15); it accounted for 11% unique variance versus 3%. The predictors correlated *r* = .60 (VIFs < 1.6).”"),
        ],

        "logistic-regression": [
            idea("Predicting a yes/no outcome",
                 "Many outcomes are **binary**: passed or failed, voted or didn't, answered correctly or not. Ordinary regression would predict values below 0 or above 1, which make no sense as probabilities. **Logistic regression** solves this by modeling a transformation of the probability.",
                 "First, probabilities become **odds**: p / (1 − p). A probability of .75 is odds of 3 (“3 to 1”). Then odds become **log-odds** (the logit), which can be any number from minus to plus infinity. The model fits a straight line on the log-odds scale: log-odds = b₀ + b₁x.",
                 "Each coefficient is the change in log-odds per unit of the predictor. That's hard to picture, so we **exponentiate** it: exp(b) is the **odds ratio (OR)** — how many times the odds multiply per unit of the predictor. OR > 1 means higher odds; OR < 1 means lower; OR = 1 means no effect.",
                 "To get back to probabilities, use p = 1 / (1 + e^−(log-odds)). The relationship between x and p is an **S-shaped curve**: probabilities change slowly near 0 and 1 and fastest in the middle."),
            analogy("Odds at the races",
                    "Betting odds of “3 to 1” mean a horse is expected to win once for every three losses — a 25% chance. An odds ratio of 2 means doubling those odds: from 3-to-1 against to 3-to-2 against. Logistic regression speaks in this language of odds."),
            worked("From coefficients to probabilities",
                   "A model gives log-odds(high anxiety) = −6 + 1.25 × rumination.",
                   "At rumination 4: −6 + 5 = −1 → p = 1 / (1 + e¹) ≈ **.27**.",
                   "At rumination 5: −6 + 6.25 = 0.25 → p = 1 / (1 + e^−0.25) ≈ **.56**.",
                   "OR = exp(1.25) ≈ **3.5**: each extra point of rumination multiplies the odds of high anxiety by 3.5. In probability terms that's a jump from .27 to .56 here — but a much smaller change near the extremes of the curve."),
            inWords("Reporting logistic regression",
                    "“Each one-point increase in rumination was associated with 3.5 times higher odds of high anxiety, OR = 3.49, 95% CI [2.6, 4.7], *p* < .001; predicted probability rose from .27 at rumination 4 to .56 at rumination 5.”"),
        ],

        "lab-hsb2": [
            idea("How to approach this lab",
                 "This lab uses a real dataset: 200 high-school students from a national survey, with test scores in five subjects plus background variables. Work through the exercises in order — each one uses a different test from this unit.",
                 "For every exercise, follow the same three steps: (1) **describe** the relevant variables (means, SDs, or counts) and make a quick plot; (2) **choose** the test that fits the design — how many groups, independent or paired, numerical or categorical outcome; (3) **report** the result in one sentence with the effect size, not just the p-value.",
                 "Because this is real data, there's no built-in answer key — the “What you should find” notes describe the results the dataset gives."),
        ],

        "lab-evals": [
            idea("How to approach this lab",
                 "This lab uses real course evaluations from a large university, where students also rated each professor's physical appearance. The question — does appearance predict evaluation scores? — is a classic example for regression.",
                 "Start with a scatterplot before fitting anything, so you can see how weak or strong the relationship is. Then build up: a simple regression, then add other predictors, then test whether the relationship differs by gender with an interaction.",
                 "Keep an eye on the design: most professors taught several courses, so courses from the same professor aren't independent. You'll learn how to handle that properly in Unit 7."),
        ],

        "lab-resume": [
            idea("How to approach this lab",
                 "This lab uses data from a famous field experiment: researchers sent thousands of fictitious résumés to real job ads, randomly assigning names that signal race and gender, and recorded which résumés got a callback.",
                 "The outcome is binary (callback or not), so start with simple proportions and a chi-square test, then move to logistic regression to include several predictors at once.",
                 "Pay attention to why this design allows a **causal** conclusion: because names were randomly assigned to otherwise similar résumés, a difference in callbacks can be attributed to the name."),
        ],

        // MARK: Unit 6 · Visualizing statistics

        "plotting-basics": [
            idea("A plot maps data to things your eyes can compare",
                 "Every statistical graphic does the same basic thing: it **maps** variables onto visual properties — position on the x-axis, position on the y-axis, color, size, shape. Our eyes are very good at comparing positions along a common axis, less good at comparing areas or colors, so the most important comparison should usually go on position.",
                 "**ggplot2** in R makes this explicit through the **grammar of graphics**: you declare the data, the **aesthetic mappings** (`aes(x = rumination, y = anxiety, colour = region)`), and then add **layers** (`geom_point()`, `geom_smooth()`). **matplotlib** in Python works with a **figure** containing **axes** that you draw on; **seaborn** adds a ggplot-like layer on top that takes a DataFrame and column names.",
                 "**Color** should have a job. Categories get distinct hues; a magnitude (like a count) gets one hue from light to dark; a signed value (like a correlation from −1 to +1) gets two hues with a neutral midpoint at 0."),
            analogy("A map legend",
                    "A map uses position for location, color for land vs. water, and line width for road size. Each visual property encodes one kind of information, and the legend tells you the mapping. A good statistical plot is designed the same way — each visual property has one clear meaning."),
            worked("Turning a question into a plot",
                   "Question: is rumination related to anxiety, and is the relationship similar in urban and rural respondents?",
                   "Two numerical variables → a **scatterplot**: rumination on x, anxiety on y.",
                   "A grouping variable → either **color** by region or separate **panels** (facets), one per region.",
                   "Facets are often clearer than color when points overlap a lot, because each panel can be read on its own."),
            inWords("Describing a figure in a caption",
                    "“Figure 1. Anxiety as a function of rumination for urban (left) and rural (right) respondents. Each point is one respondent; lines show least-squares fits with 95% confidence bands.” A caption should let someone understand the figure without reading the text."),
        ],

        "plotting-groups": [
            idea("Show the data, not just the averages",
                 "The traditional bar chart of group means hides almost everything: how many people are in each group, how spread out they are, whether there are outliers or clusters. Two groups with the same mean bars could look completely different in the raw data.",
                 "Better practice is to show **individual data points** (jittered so they don't overlap) together with a **summary** — the mean with a 95% confidence interval, or a boxplot. Violin plots add the shape of the distribution.",
                 "For **within-person** designs (the same people before and after), connect each person's measurements with a thin line. Readers can then see whether most people changed in the same direction — the information a paired test actually uses."),
            analogy("A class photo vs. an average face",
                    "A bar of the mean is like describing a class by computing one “average face.” Showing the raw points is the class photo: you see every individual, how varied they are, and whether a few people stand out."),
            worked("Choosing error bars",
                   "Three kinds of error bars look identical but mean very different things.",
                   "**SD** bars show how much individuals vary — they don't shrink with more data.",
                   "**SE** bars show the precision of the mean (SD / √n); they're about half the width of a 95% CI.",
                   "**95% CI** bars show a plausible range for the population mean. Always say in the caption which one you're using; 95% CIs are usually the most informative."),
            inWords("A caption for a group comparison",
                    "“Post-test scores by teaching method. Dots are individual students; black points and bars show means with 95% confidence intervals.”"),
        ],

        "plotting-relationships": [
            idea("Showing how one variable changes with another",
                 "For two numerical variables, the **scatterplot** is the starting point. Adding a **regression line** with a confidence band summarizes the linear trend; adding a **smoother** (loess) shows whether the trend is actually curved.",
                 "Interactions are easiest to understand as **simple-slopes plots**: predicted outcome lines drawn at a few values of the moderator (for example, low, average, and high mindfulness). Lines that aren't parallel show the interaction directly.",
                 "A **correlation heatmap** displays many correlations at once. Because correlations are signed, use a **diverging** color scale centered on 0 with the limits fixed at −1 and +1, so weak correlations don't look strong."),
            analogy("Contour lines on a hiking map",
                    "A simple-slopes plot is like showing the same trail at three different times of year: the route is the same, but how steep it feels changes with the season. The moderator is the season; the slope of each line is how steep the trail feels."),
            worked("Reading a simple-slopes plot",
                   "Three lines show predicted rumination across social media use at low, average, and high mindfulness.",
                   "The low-mindfulness line rises steeply (slope 0.7); the average line rises moderately (0.5); the high-mindfulness line rises gently (0.3).",
                   "So social media use is related to rumination at every level, but the relationship weakens as mindfulness increases — a negative interaction of −0.2 per SD of mindfulness."),
            inWords("Describing an interaction plot",
                    "“Figure 2. Predicted rumination as a function of social media use at low (−1 SD), average, and high (+1 SD) mindfulness. The positive association weakened as mindfulness increased.”"),
        ],

        "plotting-models": [
            idea("Plot what the model estimated",
                 "Tables of coefficients are hard to scan. A **coefficient plot** shows each estimate as a dot with its confidence interval as a bar, all on one axis with a reference line at 0 (or at 1 for odds ratios). Readers can see at a glance which effects are large, which are precise, and which intervals cross the line of “no effect.”",
                 "For models whose coefficients are hard to interpret directly — logistic, ordinal, multinomial — plot **predicted probabilities** instead: the S-curve of a logistic model, stacked bars of predicted rating categories, or a heatmap of transition probabilities.",
                 "Odds ratios belong on a **log scale**, so that an OR of 2 and an OR of 0.5 — equal-sized effects in opposite directions — sit the same distance from 1."),
            analogy("A scoreboard",
                    "A coefficient plot is a scoreboard for your predictors: each row is a player, the dot is their score, and the bar shows how sure we are of it. A bar that crosses zero means we can't tell that player from someone who isn't playing."),
            worked("Reading a coefficient plot",
                   "Rows: rumination β = 0.48 [0.39, 0.57]; social media β = 0.14 [0.04, 0.24]; phone checking β = 0.03 [−0.07, 0.13].",
                   "Rumination's interval is far from 0 — a strong, precise effect.",
                   "Social media's interval is above 0 but close to it — a small effect.",
                   "Phone checking's interval crosses 0 — no clear evidence of an effect once the others are held constant."),
            inWords("Captioning a model figure",
                    "“Figure 3. Standardized coefficients (β) with 95% confidence intervals from a regression of anxiety on all predictors. The dashed line marks β = 0.”"),
        ],

        "publication-figures": [
            idea("Figures that survive printing, shrinking, and every reader",
                 "A figure in a journal is often printed at one column wide (about 3.5 inches), sometimes in grayscale, and read by people with color-vision deficiencies. Designing for those conditions from the start saves painful revisions.",
                 "Define one **style** for the whole paper — fonts, sizes, colors — and reuse it. Use a **colorblind-safe palette** (such as Okabe–Ito) and never rely on color **alone**: add direct labels, different shapes, or line styles.",
                 "Export at the final printed size, either as a vector format (**PDF** or **SVG**, which stays sharp at any zoom) or as a high-resolution image (**300 dpi** or more). Avoid common distortions: truncated bar axes, 3-D effects, pie charts, and dual y-axes."),
            analogy("Writing for an audience",
                    "Just as you'd write differently for a talk than for a paper, a figure has to be designed for where it will be seen. A figure that looks fine on a large monitor can become unreadable when shrunk to one journal column."),
            worked("Getting the size right",
                   "You make a figure at 7 × 5 inches with 10-point text, then shrink it to a 3.5-inch column.",
                   "Everything scales by half — the text is now **5 points**, too small to read.",
                   "Instead, set the figure size to 3.5 × 2.8 inches in the code and keep the text at 9–10 points. The figure is then drawn at its final size, and nothing shrinks."),
            inWords("A figure checklist sentence",
                    "“All figures use the Okabe–Ito palette with direct labels, error bars show 95% CIs, and figures were exported as vector PDFs at single-column width.” Many journals ask for exactly these details."),
        ],
    ]
}
