import Foundation

// Beginner-level explanations for Units 7–11.

extension Curriculum {
    static let explanationsAdvanced: [String: [ExplanationSection]] = [

        // MARK: Unit 7 · Measurement & multilevel models

        "mixed-models": [
            idea("When observations come in clusters",
                 "Most of the tests so far assume every observation is **independent** — knowing one tells you nothing about another. That's often false. Each participant answers many trials; each student sits in a classroom with other students; each word is read by many participants. Observations from the same cluster are more alike than observations from different clusters.",
                 "Ignoring this has a cost: the analysis acts as if you had much more independent information than you do, so standard errors are too small and p-values too optimistic. Averaging each cluster down to one number throws information away instead.",
                 "**Mixed-effects (multilevel) models** handle clusters directly. They contain **fixed effects** — the average relationships you want to generalize, like the effect of condition — and **random effects** — how much clusters differ from that average. A **random intercept** lets each participant have their own baseline; a **random slope** lets each participant's effect of a predictor differ.",
                 "Rather than estimating a separate parameter for every participant, the model estimates **how much** participants vary (the random-effect variance). Participants with little data are pulled toward the overall average — called **shrinkage** — a sensible compromise.",
                 "When participants and items are both sampled (every participant sees every word), use **crossed random effects** for both, so conclusions generalize to new people **and** new items."),
            analogy("Students in schools",
                    "Test scores vary between students, but they also vary between schools — some schools score higher across the board. A multilevel model is like describing each student as “their school's typical level, plus how they differ from their schoolmates.” The fixed effects describe the system as a whole; the random effects describe how schools (and students) differ around it."),
            worked("Random intercepts in numbers",
                   "Average wellbeing across all participants is 4.0, and each extra hour of work above someone's usual lowers it by 0.25 (the fixed effects).",
                   "Participant A's random intercept is +0.6: on a typical day, A sits at 4.0 + 0.6 = **4.6**.",
                   "Participant B's random intercept is −0.4: B's typical day is **3.6**.",
                   "On a day with 2 extra hours, A is predicted at 4.6 − 0.5 = **4.1** and B at 3.6 − 0.5 = **3.1**. Same slope, different starting points. With a random slope too, the 0.25 could be, say, 0.15 for A and 0.35 for B."),
            inWords("Reporting a mixed model",
                    "“We fit a linear mixed model, wellbeing ~ hours_within + (1 + hours_within | participant), using REML (lme4). Within persons, an extra hour of work predicted lower wellbeing, *b* = −0.25, 95% CI [−0.29, −0.21]. Participants varied in baseline wellbeing (SD = 0.69) and in the size of this effect (SD = 0.12).”"),
        ],

        "mixed-logistic": [
            idea("Yes/no outcomes measured many times",
                 "Combine the last two big ideas. **Logistic regression** handles binary outcomes (correct/incorrect) on the log-odds scale. **Mixed models** handle clustering with random effects. A **mixed logistic regression** (a generalized linear mixed model) does both at once.",
                 "Each participant gets a random intercept on the log-odds scale — some people are more accurate overall — and each item gets one too — some questions are harder. The fixed effects then describe a **typical** participant answering a **typical** item.",
                 "A useful special case: the **intercept alone** tells you whether the probability differs from 50%. Log-odds of 0 means p = .5, so testing the intercept against 0 tests “is accuracy above chance?”",
                 "An alternative, **GEE**, estimates **population-average** effects with standard errors corrected for clustering. For logistic models, mixed-model (typical-person) effects are usually a little larger than GEE (population-average) effects, because averaging S-curves flattens them."),
            analogy("A quiz show with many contestants and many questions",
                    "Some contestants are generally better (participant random intercepts) and some questions are generally harder (item random intercepts). To ask whether a type of question is harder in general, you need to account for both — otherwise one very strong contestant or a few very hard questions could drive the result."),
            worked("Converting the intercept",
                   "A model of comprehension accuracy has an intercept of **1.39** for simple sentences and a coefficient of **−0.50** for complex sentences.",
                   "Simple: p = 1 / (1 + e^−1.39) ≈ **.80**.",
                   "Complex: log-odds = 1.39 − 0.50 = 0.89 → p ≈ **.71**.",
                   "Odds ratio = e^−0.50 ≈ **0.61**: complex sentences multiply the odds of a correct answer by about 0.6."),
            inWords("Reporting a mixed logistic model",
                    "“A logistic mixed model with crossed random intercepts for participants and items showed lower accuracy for complex sentences, OR = 0.61, 95% CI [0.47, 0.79], *p* < .001; predicted accuracy was .80 for simple and .71 for complex sentences.”"),
        ],

        "scale-scoring": [
            idea("Turning questionnaire items into one score",
                 "A single question rarely measures something like anxiety or mindfulness well — answers depend on wording and mood. So questionnaires ask **several items** about the same construct and combine them into a **scale score**, usually the mean of the items.",
                 "First, make sure every item points the same way. Some items are **reverse-worded** (“I often act on autopilot” on a mindfulness scale), so agreeing means *less* of the construct. Recode them so that a high number always means more: on a 1–5 scale, the recoded value is 6 − x.",
                 "Next, handle **missing items**. A common rule is to average the items a person answered, as long as they answered most of them (say, at least 80%); otherwise their score is missing. Decide the rule in advance.",
                 "Finally, check that the items **hang together**. **Cronbach's α** estimates internal consistency from how strongly the items correlate; values around .70–.90 are typical for research scales. **Item–rest correlations** show whether any single item doesn't fit — a negative one almost always means a reverse item wasn't recoded."),
            analogy("Averaging several judges",
                    "A diving competition uses several judges and averages their scores, because any one judge might be off. Questionnaire items are the judges of a construct. Reverse-worded items are judges scoring on an upside-down card — you have to flip their scores before averaging."),
            worked("Scoring one respondent",
                   "Six mindfulness items on a 1–5 scale; items 3 and 5 are reverse-worded. A respondent answers 4, 4, 2, 5, 1, and leaves item 6 blank.",
                   "Recode: item 3 becomes 6 − 2 = **4**; item 5 becomes 6 − 1 = **5**.",
                   "Keyed answers: 4, 4, 4, 5, 5 — five of six items, which meets a “at least 5 items” rule.",
                   "Score = (4 + 4 + 4 + 5 + 5) / 5 = **4.4**."),
            inWords("Reporting a scale",
                    "“Mindfulness was measured with six items (1–5; items 3 and 5 reverse-keyed). Scores were the mean of answered items for respondents completing at least five (*n* = 370); α = .81.”"),
        ],

        "reliability": [
            idea("Does a scale measure one thing, and how consistently?",
                 "**Reliability** is about consistency: would the scale give similar scores if you could measure the same people again? **Validity** is about meaning: does it measure what it claims to? A scale can be reliable but not valid (consistently measuring the wrong thing), but it can't be valid without being reliable.",
                 "**Cronbach's α** and **McDonald's ω** estimate internal-consistency reliability. ω is often preferred because α assumes every item is an equally good measure of the construct.",
                 "**Factor analysis** asks what structure explains the correlations among items. It models each item as partly reflecting an underlying **factor** (the construct) and partly unique noise. Each item's **loading** says how strongly it reflects the factor. **Exploratory factor analysis (EFA)** discovers the structure from the data; **confirmatory factor analysis (CFA)** tests a structure you specify in advance.",
                 "How many factors? **Parallel analysis** compares the data's pattern with random data and keeps the factors that stand out — plus judgment about whether the factors make substantive sense."),
            analogy("Several thermometers in one room",
                    "Imagine five slightly imperfect thermometers in the same room. Their readings all rise and fall together because they respond to the same underlying temperature (the factor). A thermometer that's well calibrated has a high loading; one that's partly affected by a draft has a lower one. If one moves opposite to the others, it's probably hung upside down — a reverse-keyed item."),
            worked("Reading factor loadings",
                   "A one-factor EFA of six items gives loadings .71, .68, .65, .70, .62, .66.",
                   "All items load substantially (above about .4) on one factor — consistent with a single construct.",
                   "If one item had loaded .15, it would barely reflect the construct and might be dropped or reworded.",
                   "If two items loaded −.6 while the rest loaded +.7, those two are almost certainly reverse-worded items that weren't recoded."),
            inWords("Reporting reliability and structure",
                    "“A one-factor EFA (oblimin, maximum likelihood) supported unidimensionality; loadings ranged from .62 to .71. Internal consistency was good, ω = .82, α = .81.”"),
        ],

        "inter-rater": [
            idea("When people do the measuring",
                 "Sometimes the measurement is a **judgment**: a teacher grading an essay, an observer rating behavior, a clinician scoring an interview. Then you need evidence that the score reflects the thing being rated, not who happened to rate it. The standard check is to have two or more raters score the same cases **independently** and measure their agreement.",
                 "**Percent agreement** is intuitive but misleading: if most essays get a 4, raters agree often just by chance. **Cohen's κ** corrects for chance agreement: κ = (observed agreement − chance agreement) / (1 − chance agreement). 0 means no better than chance; 1 means perfect. **Weighted κ** gives partial credit for near-misses on ordered scales.",
                 "**Krippendorff's α** generalizes the idea to any number of raters, missing ratings, and different kinds of scales. Common guidelines treat α ≥ .80 as reliable and .67–.80 as acceptable for tentative conclusions.",
                 "For continuous scores, the **intraclass correlation (ICC)** asks what share of the score variance reflects real differences between cases. An **absolute-agreement** ICC counts it as error if one rater is systematically harsher; a **consistency** ICC doesn't."),
            analogy("Two referees",
                    "Two referees watching the same match should call most fouls the same way. If they agree only as often as two people flipping coins would, their calls tell you nothing. If one always calls more fouls than the other but they agree on *which* plays were the worst, their calls are consistent but not in absolute agreement."),
            worked("Cohen's κ by hand",
                   "Two raters classify 100 essays as pass or fail. They agree on 85: both say pass for 60, both fail for 25.",
                   "Rater A says pass for 70 essays; rater B for 65.",
                   "Chance agreement = P(both pass) + P(both fail) = (.70 × .65) + (.30 × .35) = .455 + .105 = **.56**.",
                   "κ = (.85 − .56) / (1 − .56) = .29 / .44 ≈ **.66**. Raters agree 85% of the time, but much of that would happen by chance; chance-corrected agreement is moderate."),
            inWords("Reporting inter-rater reliability",
                    "“Two trained raters independently scored all 120 essays (1–6 rubric). Agreement was good (weighted κ = .78; ordinal Krippendorff's α = .77). Rater B scored slightly higher on average (0.3 points), so final scores averaged both raters.”"),
        ],

        "reporting": [
            idea("An analysis isn't finished until it's reported",
                 "Readers can only trust and reuse your findings if they can see exactly what you did. Good reporting describes the **sample** (and every exclusion), the **measures**, the **analysis** (the exact model, with its assumptions checked), and the **results** (effect sizes with confidence intervals, not just p-values).",
                 "**Open science** practices make this easier to trust. **Preregistration** records your hypotheses and analysis plan before you see the data, so readers can tell planned tests from discoveries made along the way. **Registered reports** go further: a journal reviews and accepts the plan before the results exist. Sharing **data and code** lets others reproduce your numbers.",
                 "These practices exist because flexible analysis can produce false findings without anyone intending to cheat. Each data-dependent choice — which outliers to remove, which covariates to add, which outcome to emphasize — is a fork in the road. Trying several and reporting the one that “works” is **p-hacking**; presenting a post-hoc idea as if it had been predicted is **HARKing**."),
            analogy("A lab notebook",
                    "A chemist records every step in a lab notebook so another chemist can repeat the experiment. A preregistration is the plan written on the first page before the experiment starts; the methods section and shared code are the notebook itself."),
            worked("The garden of forking paths",
                   "Suppose there's truly no effect, and an analyst can choose among 2 outlier rules × 2 covariate sets × 2 outcomes = **8** reasonable analyses.",
                   "Each has a 5% false-positive rate. If the analyses were independent, the chance that **at least one** is significant would be 1 − .95⁸ ≈ **34%**.",
                   "In practice the analyses are correlated, so the real rate is lower — but still well above 5%. Fixing the analysis in advance keeps it at 5%."),
            inWords("A transparent results paragraph",
                    "“As preregistered, we compared methods with an ANCOVA adjusting for pre-test scores. Active learning outperformed lecture, *b* = 4.6, 95% CI [1.9, 7.3], *p* = .001. An exploratory analysis (not preregistered) suggested…” Labeling exploratory analyses as such is the key habit."),
        ],

        // MARK: Unit 8 · Moderation & mediation

        "moderation": [
            idea("When an effect depends on something else",
                 "**Moderation** means the relationship between X and Y **changes** depending on a third variable, W (the moderator). Perhaps social media use is strongly linked to rumination for people low in mindfulness, but only weakly for people high in mindfulness.",
                 "You test moderation by adding the **product** of X and W to a regression: Y = b₀ + b₁X + b₂W + b₃(X × W). The interaction coefficient **b₃** is the test: it says how much the slope of X changes for each one-unit increase in W. If b₃ is 0, the slope of X is the same at every level of W.",
                 "With an interaction in the model, b₁ is no longer “the effect of X” — it's the effect of X **when W equals 0**. That's why we **mean-center** X and W first (subtract their means), so b₁ becomes the effect of X at the **average** W.",
                 "To describe an interaction, compute **simple slopes**: the slope of X at chosen values of W, such as one SD below the mean, at the mean, and one SD above. Plotting those lines is the clearest way to show the pattern."),
            analogy("Fertilizer and rain",
                    "Fertilizer helps plants grow — but how much depends on rainfall. In a dry season it barely helps; in a wet season it helps a lot. Rainfall **moderates** the effect of fertilizer. A model without the fertilizer × rain interaction would report one average effect that's wrong in both seasons."),
            worked("Computing simple slopes",
                   "A centered model gives: rumination = 4.0 + **0.50** × social media − 0.20 × mindfulness − **0.20** × (social media × mindfulness). Mindfulness has SD = 1.",
                   "At average mindfulness (W = 0): slope = 0.50.",
                   "At high mindfulness (W = +1): slope = 0.50 − 0.20 × 1 = **0.30**.",
                   "At low mindfulness (W = −1): slope = 0.50 − 0.20 × (−1) = **0.70**. The link between social media and rumination is more than twice as strong for less mindful people."),
            inWords("Reporting moderation",
                    "“Mindfulness moderated the association between social media use and rumination, *b* = −0.20, 95% CI [−0.30, −0.10], *p* < .001. Simple slopes were 0.70 at low (−1 SD), 0.50 at average, and 0.30 at high (+1 SD) mindfulness (all *p* < .001).”"),
        ],

        "mediation": [
            idea("When an effect runs through something else",
                 "**Mediation** asks **how** or **why** X relates to Y. The idea is that X affects a **mediator** M, which in turn affects Y: social media use → rumination → anxiety.",
                 "Two regressions estimate the pieces. Regress M on X to get path **a** (how much X changes M). Regress Y on both M and X to get path **b** (how much M changes Y, holding X constant) and the **direct effect c′** (the part of X's effect that doesn't go through M).",
                 "The **indirect effect** is **a × b**. Together, the **total effect** of X on Y is c = c′ + a × b.",
                 "Because a product of two estimates isn't normally distributed, its significance is tested with a **bootstrap confidence interval** (Unit 3): resample the data thousands of times, recompute a × b each time, and check whether the middle 95% excludes 0.",
                 "A big caution: statistics can show that data are **consistent** with X → M → Y, but they can't establish the causal order. That needs design — randomizing X, measuring variables over time, or strong theory."),
            analogy("Dominoes",
                    "Knocking over the first domino (X) topples the second (M), which topples the third (Y). The indirect effect is the push that travels through the middle domino. If you also gave the third domino a direct nudge, that's the direct effect. Mediation analysis estimates how much of the final fall came through the chain."),
            worked("Splitting a total effect",
                   "Path a: each point of social media use predicts **0.60** more rumination.",
                   "Path b: each point of rumination predicts **0.45** more anxiety, holding social media constant.",
                   "Indirect effect = 0.60 × 0.45 = **0.27**. Direct effect c′ = **0.15**.",
                   "Total effect = 0.15 + 0.27 = **0.42**. About 0.27 / 0.42 ≈ 64% of the total association runs through rumination."),
            inWords("Reporting mediation",
                    "“Social media use was indirectly associated with anxiety through rumination, *ab* = 0.27, 95% bootstrap CI [0.19, 0.36] (10,000 resamples). A direct association remained, *c*′ = 0.15, 95% CI [0.05, 0.25]. Because the data are cross-sectional, these results are consistent with, but don't establish, a causal pathway.”"),
        ],

        "moderated-mediation": [
            idea("When an indirect effect depends on a third variable",
                 "Put the last two lessons together. If W moderates one of the paths in a mediation model, then the **indirect effect itself** changes with W. This is **moderated mediation** (also called a conditional process model).",
                 "In **first-stage** moderated mediation (Hayes' PROCESS Model 7), W moderates the a path: the effect of X on M is a₁ + a₃W. The indirect effect at any value of W is then **(a₁ + a₃W) × b** — the **conditional indirect effect**.",
                 "The formal test is the **index of moderated mediation**, a₃ × b: how much the indirect effect changes for each one-unit increase in W. If its bootstrap CI excludes 0, the indirect effect genuinely differs across levels of W.",
                 "A common mistake is to show that the indirect effect is significant at one level of W and not at another, and call that moderated mediation. A difference in significance isn't a significant difference — only the index tests it."),
            analogy("A pipeline with an adjustable valve",
                    "Water flows from a reservoir (X) through a pipe (M) to a tap (Y). A valve on the first section of pipe (W) controls how much flows through. Open the valve and the indirect flow is large; close it partway and it shrinks. The index of moderated mediation measures how much the flow changes per turn of the valve."),
            worked("Indirect effects at three levels",
                   "a₁ = 0.50, a₃ = −0.20 (per SD of mindfulness), b = 0.45.",
                   "Low mindfulness (W = −1): (0.50 + 0.20) × 0.45 = **0.32**.",
                   "Average (W = 0): 0.50 × 0.45 = **0.23**.",
                   "High (W = +1): (0.50 − 0.20) × 0.45 = **0.14**. Index = −0.20 × 0.45 = **−0.09**: each SD of mindfulness shrinks the indirect effect by 0.09."),
            inWords("Reporting moderated mediation",
                    "“The indirect effect of social media use on anxiety through rumination was moderated by mindfulness, index = −0.09, 95% bootstrap CI [−0.15, −0.04]. Conditional indirect effects were 0.32 at low, 0.23 at average, and 0.14 at high mindfulness.”"),
        ],

        // MARK: Unit 9 · Categorical & ordinal outcomes

        "ordinal-models": [
            idea("Rating scales are ordered, but not evenly spaced",
                 "A 1–7 acceptability rating has a clear order — 6 is more acceptable than 5 — but nothing guarantees that the step from 1 to 2 is the same size as the step from 6 to 7. Responses also tend to pile up at certain points. Treating ratings as ordinary numbers (computing means, fitting linear models) can therefore distort results.",
                 "An **ordinal (cumulative link) model** assumes each rating comes from a hidden, continuous judgment that gets cut into categories at **thresholds**. The model estimates where those thresholds are from the data, so unequal spacing is no problem.",
                 "Predictors shift the hidden judgment up or down. A positive coefficient means higher ratings are more likely; exp(coefficient) is an **odds ratio**: the odds of giving a higher rating rather than a lower one, at any cut point. The **proportional odds** assumption is that a predictor shifts every threshold by the same amount.",
                 "Add random effects for **participants** (some people use the high end of the scale) and **items** (some sentences sound better overall) and you get an ordinal mixed model (`clmm` in R)."),
            analogy("A thermometer with only a few markings",
                    "Imagine a thermometer marked only “cold,” “cool,” “mild,” “warm,” and “hot.” The real temperature is continuous, but you only see which band it falls in, and the bands may be different widths. An ordinal model estimates both where the band boundaries are and how much a predictor raises the underlying temperature."),
            worked("From the hidden scale to category probabilities",
                   "Suppose the threshold between “4 or below” and “5 or above” sits at 0 on the hidden scale, and simple sentences have a hidden mean of +0.6.",
                   "With a logistic spread, P(rating ≥ 5) = 1 / (1 + e^−0.6) ≈ **.65** for simple sentences.",
                   "Complex sentences have a hidden mean of −0.6: P(rating ≥ 5) ≈ **.35**.",
                   "The odds of a high rating are .65/.35 ≈ 1.86 for simple and .35/.65 ≈ 0.54 for complex: an odds ratio of about **0.29** for complex vs. simple, and the same ratio applies at every threshold under proportional odds."),
            inWords("Reporting an ordinal model",
                    "“A cumulative link mixed model with crossed random intercepts showed that complex sentences received lower ratings, OR = 0.25, 95% CI [0.19, 0.33], and that the effect of distance was larger for complex sentences, OR_interaction = 0.45, 95% CI [0.31, 0.66].” Category probabilities make a helpful figure."),
        ],

        "multinomial": [
            idea("Choosing among several unordered options",
                 "Some outcomes are **categories with no order**: commute mode (car, bus, bike, walk), which of several products someone buys, which dialect form a speaker uses. Logistic regression handles two categories; **multinomial logistic regression** handles more.",
                 "It picks a **reference category** (say, car) and fits a separate set of coefficients for each other category, each describing the log-odds of choosing **that** option **instead of** the reference. With four categories you get three sets of coefficients.",
                 "When the same people choose repeatedly (every week for ten weeks), their choices aren't independent — habits and preferences carry over. Two tools help. A **transition matrix** describes how often people move from each choice to each other choice from one occasion to the next. A **multinomial mixed model** adds random intercepts for each person to account for their stable preferences."),
            analogy("Choosing lunch",
                    "Every day you choose between a sandwich, a salad, or soup. A multinomial model asks how factors like the weather change the odds of soup *versus* a sandwich, and of salad *versus* a sandwich. A transition matrix asks: after a soup day, how often is the next day soup again?"),
            worked("Reading one coefficient",
                   "With car as the reference, the coefficient for **walk** on distance is **−0.6** per kilometer.",
                   "Odds ratio = e^−0.6 ≈ **0.55**: each extra kilometer multiplies the odds of walking rather than driving by 0.55.",
                   "Over 3 extra kilometers: 0.55³ ≈ **0.17** — about one-sixth the odds.",
                   "This says nothing directly about walk vs. bus. For that comparison, refit with bus as the reference (or subtract the two coefficients)."),
            inWords("Reporting a multinomial model",
                    "“Relative to driving, longer distances were associated with much lower odds of walking (OR = 0.55 per km, 95% CI [0.47, 0.64]) and somewhat lower odds of biking (OR = 0.84). The odds of biking rather than driving increased over the study weeks (OR = 1.17 per week).”"),
        ],

        // MARK: Unit 10 · Latent class & profile models

        "latent-class": [
            idea("Finding hidden types in yes/no answers",
                 "Sometimes we suspect people fall into **types** that nobody has labeled — kinds of studiers, patterns of health behavior, styles of media use. **Latent class analysis (LCA)** finds such types from several **categorical** variables.",
                 "“Latent” means hidden: we never observe anyone's class directly. LCA assumes the sample is a mix of a few classes, and that each class has its own **probability** of answering yes to each item. Within a class, the items are assumed unrelated to each other (**local independence**) — all of the connections between items are explained by which class people belong to.",
                 "The model estimates three things: the **size** of each class, each class's **item probabilities** (its profile), and each person's **posterior probability** of belonging to each class.",
                 "You don't know in advance how many classes there are, so you fit models with 1, 2, 3, … classes and compare them using fit statistics (especially **BIC**, lower is better), how cleanly people are assigned (**entropy**), class sizes, and whether each class makes substantive sense."),
            analogy("Sorting a mixed bag of seeds",
                    "Imagine a bag of seeds from three plant species, but the labels have fallen off. Each species tends to have a typical color, size, and shape, though individual seeds vary. By looking at which features tend to go together, you can work out that there are three kinds and estimate which kind each seed probably is. LCA does the same with people's answers."),
            worked("Reading a class profile",
                   "A three-class model of six study strategies gives this class: rereads .90, takes notes .85, self-tests .15, spaces practice .10, explains .10, studies with peers .20; size 45%.",
                   "This class mostly rereads and takes notes and rarely uses active strategies — a natural name is **“passive review.”**",
                   "A student who rereads and takes notes but never self-tests might have posterior probabilities of .92 (passive), .05 (active), .03 (social): they're assigned to passive review with high certainty.",
                   "Average posterior probabilities above about .80 for each class indicate the classes are well separated."),
            inWords("Reporting an LCA",
                    "“Models with one to six classes were compared. The three-class solution had the lowest BIC and interpretable classes (entropy = .78): passive review (45%), active practice (35%), and social learning (20%).”"),
        ],

        "latent-profile": [
            idea("Hidden types from continuous scores",
                 "**Latent profile analysis (LPA)** is LCA's sibling for **continuous** variables such as scale scores. Instead of each class having probabilities for yes/no items, each **profile** has its own **mean** on each variable (and, depending on the model, its own variances).",
                 "Both LCA and LPA are **finite mixture models**: they treat the data as a mixture of a small number of subgroups and work out which mixture best explains the observed scores.",
                 "The workflow is the same as for LCA: fit 1, 2, 3, … profiles; compare BIC, entropy, profile sizes, and interpretability; and name each profile by its pattern of means — for example, a “thriving” profile high in wellbeing, support, and sleep but low in stress.",
                 "One extra decision in LPA is the **variance structure**: whether profiles share the same variances (the simplest, and Mplus's default) or each has its own. More flexible structures add many parameters, so compare a few chosen in advance."),
            analogy("Musical genres",
                    "Songs can be described by continuous features: tempo, loudness, how acoustic they sound. Without any labels, you might find clusters — fast and loud (rock), slow and acoustic (folk), fast and electronic (dance). Each cluster has typical values on each feature. LPA finds those clusters in people's scores."),
            worked("Comparing models with BIC",
                   "BIC for 1–5 profiles: 5,346; 4,512; 4,294; 4,316; 4,338.",
                   "BIC drops sharply from 1 to 2 and again from 2 to 3 profiles, then rises.",
                   "The lowest value is at **3 profiles**; adding a fourth improves fit too little to justify its extra parameters.",
                   "If the 3-profile solution also had sensible profiles and none smaller than about 5%, you'd choose it."),
            inWords("Reporting an LPA",
                    "“LPA with equal variances and zero covariances favored three profiles (lowest BIC; entropy = .90): thriving (50%), average (30%), and struggling (20%; low wellbeing and sleep, high stress).”"),
        ],

        "mplus-mixtures": [
            idea("Why many researchers fit mixture models in Mplus",
                 "LCA and LPA are harder to estimate than ordinary regressions. Their fit has many **local maxima** — the estimation can get stuck on a solution that looks good locally but isn't the best overall. **Mplus** is specialized software with robust tools for this, which is why it's often the reference choice for mixture models.",
                 "**Random starts** run the estimation from many different starting points; a trustworthy solution is one where the best result was reached from several of them (“the best loglikelihood was replicated”).",
                 "Mplus also offers **likelihood-ratio tests** for choosing the number of classes: the **LMR** test (TECH11) and the **bootstrapped LRT** (TECH14) compare a K-class model with a K − 1 class model.",
                 "Finally, Mplus implements **three-step methods** for relating classes to other variables. Putting predictors or outcomes directly into the mixture model can change what the classes are; the three-step approach settles the classes first, then relates them to covariates (**R3STEP**) or outcomes (**BCH**, **DCON**, **DCAT**) while correcting for classification uncertainty."),
            analogy("Searching for the highest peak in fog",
                    "Finding the best mixture solution is like looking for the highest point in a foggy mountain range. Walk uphill from one starting point and you'll reach *a* peak, but maybe not the highest. Start from hundreds of points, and if many of them end up on the same summit, you can be fairly sure it's the tallest. That's what STARTS and “replicated loglikelihood” do."),
            worked("Reading an enumeration table",
                   "K = 2: BIC 3,650, LMR p < .001, BLRT p < .001, smallest class 41%.",
                   "K = 3: BIC 3,598, LMR p = .004, BLRT p < .001, smallest class 21%.",
                   "K = 4: BIC 3,622, LMR p = .38, BLRT p = .09, smallest class 6%.",
                   "BIC is lowest at **3**, both tests favor 3 over 2, and neither favors 4 over 3. Choose **three classes**."),
            inWords("Reporting an Mplus mixture model",
                    "“Models were estimated in Mplus 8.10 with 500 initial and 100 final-stage random starts; the best loglikelihood was replicated for all models. Fit indices (BIC, aBIC, LMR, BLRT) favored three classes. Distal outcomes were compared across classes with the BCH method.”"),
        ],

        // MARK: Unit 12 · Capstone

        "which-test": [
            idea("Choosing an analysis is a short series of questions",
                 "Beginners often memorize a list of tests. It's easier to ask four questions about the design, in order.",
                 "**1. What type is the outcome?** A number (score, time) → means, regression, ANOVA. Two categories (yes/no) → logistic regression. Ordered categories (a rating scale) → an ordinal model. Unordered categories (choices) → a multinomial model.",
                 "**2. What are you comparing or predicting with?** Two groups → t-test. Three or more groups → ANOVA. A baseline measure as well → ANCOVA. A numerical predictor → correlation or regression. Several predictors → multiple regression.",
                 "**3. Are the observations independent?** If the same people (or items, classrooms, schools) contribute several observations, use a paired test or a mixed model — and separate between- and within-person effects for repeated measures.",
                 "**4. Is there a third variable in the story?** “Depends on” → moderation (an interaction). “Through” or “because of” → mediation. “Types of people” → latent class or profile analysis."),
            worked("Applying the four questions",
                   "Scenario: students rate how much they enjoy 20 different reading passages on a 1–7 scale, and you want to know whether longer passages are enjoyed less.",
                   "1. Outcome: a 1–7 rating → **ordinal**.",
                   "2. Predictor: passage length, a number → a **slope** in a regression-type model.",
                   "3. Independence: every student rates every passage → **crossed random effects** for students and passages.",
                   "4. No third variable. Answer: an **ordinal mixed model** (clmm) of rating on length with random intercepts for students and passages."),
        ],

        // MARK: Unit 11 · Text as data

        "clustering": [
            idea("Turning text into numbers, then grouping it",
                 "Computers can't compare sentences directly, so text analysis starts by turning each text into a list of numbers. Modern **sentence embeddings** do this by placing texts with similar **meaning** close together in a space with hundreds of dimensions — “Fold the egg whites into the batter” ends up near “Whisk the cream,” far from “Heavy rain is expected tonight.”",
                 "**Cosine similarity** measures how close two embeddings are: 1 means pointing in the same direction (very similar meaning), around 0 means unrelated.",
                 "**Clustering** then groups texts that are close together. **k-means** splits the data into a number of groups, k, that you choose, by repeatedly assigning each text to the nearest group center and moving the centers. The **silhouette** score (−1 to +1) measures how well each text fits its own group compared with the next-nearest group; you pick the k with the highest average. **HDBSCAN** finds dense groups without fixing k and labels one-off texts as **noise**.",
                 "A **medoid** — the real text closest to the center of a cluster — makes a good example to describe each group."),
            analogy("Sorting books on a table",
                    "Imagine spreading books on a huge table so that books on similar topics sit near each other: cookbooks in one corner, weather guides in another, fitness books in a third. Embeddings are the coordinates on that table; clustering draws circles around the piles; the medoid is the most typical book in each pile."),
            worked("Cosine similarity in two dimensions",
                   "Real embeddings have hundreds of dimensions, but the idea works in two. Text A = (3, 4), text B = (6, 8), text C = (4, −3).",
                   "A and B point in exactly the same direction: cosine = (3×6 + 4×8) / (5 × 10) = 50 / 50 = **1.0**.",
                   "A and C: (3×4 + 4×−3) / (5 × 5) = 0 / 25 = **0** — perpendicular, unrelated.",
                   "Length doesn't matter — B is twice as long as A — only direction, which is why cosine is used for meaning."),
            inWords("Reporting a clustering analysis",
                    "“Texts were embedded with all-MiniLM-L6-v2 and clustered with k-means; k = 3 maximized the average silhouette (.41). Cluster medoids are shown in Table 2. HDBSCAN produced a similar three-group solution (ARI = .86).”"),
        ],

        "keyness": [
            idea("Which words are characteristic of one group's texts?",
                 "**Keyness** analysis compares two collections of texts (corpora) and ranks words by how much more often they appear in one than the other. It's a quick way to see what distinguishes, say, beginner and expert questions, or two genres.",
                 "Raw counts mislead in two ways. Corpora differ in size, so counts must be turned into rates. And **rare words** produce wild ratios: a word used twice in one corpus and never in the other looks infinitely distinctive, but that's mostly chance.",
                 "The **weighted log-odds ratio with an informative Dirichlet prior** (Monroe et al., 2008) fixes both problems. It adds a small number of “pseudo-counts” to every word based on how common the word is overall, which shrinks rare-word estimates toward zero. Dividing by the uncertainty gives a **z-score**: large positive means distinctive of the first corpus, large negative of the second.",
                 "Keyness is **exploratory**: it suggests which words might matter. Test those ideas with new data before treating them as findings."),
            analogy("Spotting a regional accent",
                    "If you overhear two groups of people and notice one group says “y'all” far more often, that word is “key” for that group. But if someone said a rare word once, you wouldn't conclude it defines their group. The Dirichlet prior is that common-sense caution, built into the math."),
            worked("Why the prior matters",
                   "Corpus A (1,000 words) uses “emulsion” 3 times; corpus B (1,000 words) uses it 0 times.",
                   "Raw log-odds: log(3/997) − log(0/1000) — undefined (infinite), because of the zero.",
                   "With a pseudo-count of 3 for “emulsion” (its pooled count): A ≈ (3 + 3) / 1,000, B ≈ (0 + 3) / 1,000, so the log-odds difference is about log(6/3) = **0.69** — distinctive, but finite.",
                   "Dividing by its uncertainty (√(1/6 + 1/3) ≈ 0.71) gives z ≈ **0.98**: a hint, not strong evidence, from so few uses."),
            inWords("Reporting keyness",
                    "“Distinctive words were identified with weighted log-odds ratios using an informative Dirichlet prior based on pooled frequencies (Monroe et al., 2008); words with |*z*| > 1.96 are listed in Table 3. These lists are exploratory.”"),
        ],
    ]
}
