import Foundation

// Beginner-level explanations for Units 0–3.

extension Curriculum {
    static let explanationsBasics: [String: [ExplanationSection]] = [

        // MARK: Unit 0 · Getting started

        "vs-code": [
            idea("What a code editor is, and why you need one",
                 "Statistics software used to mean clicking through menus. Modern research does almost everything in **code** instead: short instructions written in a language such as Python or R that load data, clean it, run analyses, and draw figures.",
                 "Code has one huge advantage over clicking: it's a **written record**. Six months from now — or when a reviewer asks how you got a number — you can rerun the exact same steps and get the exact same answer. That property is called **reproducibility**, and it's now expected in research.",
                 "A **code editor** such as VS Code is where you write and run that code. Think of it as a word processor designed for code: it colors different parts of the code so they're easier to read, points out mistakes, and lets you run a line with a keystroke."),
            analogy("A recipe, a kitchen, and a cook",
                    "Your **script** (the `.py` or `.R` file) is a recipe: a list of steps written down so anyone can follow them.",
                    "The **interpreter** (Python or R itself) is the cook who actually carries out each step.",
                    "**VS Code** is the kitchen — the place where the recipe and the cook meet. **Packages** are specialized appliances (pandas for handling tables, ggplot2 for figures) that you install once and then pull out whenever a recipe calls for them."),
            worked("Your first session, step by step",
                   "1. Open VS Code and choose **File → Open Folder**, then pick a new, empty folder called `stats-practice`. Everything for your project will live here.",
                   "2. Create a file called `hello.py` (or `hello.R`) and type a single line: `print(2 + 2)` in Python, or `2 + 2` in R.",
                   "3. Run it. Python: click the ▷ button at the top right. R: put your cursor on the line and press Cmd/Ctrl + Enter.",
                   "4. A panel opens at the bottom (the **terminal**) and shows `4`. You've just written and run a program. Every analysis in this course is the same idea — just longer."),
            inWords("Describing your workflow in a methods section",
                    "“All analyses were conducted in R 4.4 (R Core Team, 2024) using the tidyverse and lme4 packages; analysis scripts are available at [link].” Writing analyses in scripts is what makes a sentence like this possible."),
        ],

        "python-vs-r": [
            idea("Two languages, one set of ideas",
                 "Python and R are both free programming languages that researchers use for statistics. They grew up differently: **R was designed by statisticians** in the 1990s, so statistical models, tables of data, and categorical variables are built into the language. **Python is a general-purpose language** — it runs websites and robots too — and gained its statistics abilities later through add-on packages.",
                 "For you as a learner, the most important point is this: **the statistics are identical**. A t-test, a regression, or a confidence interval means exactly the same thing in either language. What differs is the spelling — like the same sentence written in two human languages.",
                 "Most of what trips beginners up isn't the statistics but small differences in **defaults** — what each language does when you don't specify otherwise. This lesson collects the ones that most often cause two analyses to disagree."),
            analogy("British and American English",
                    "Python and R are like British and American English. Almost everything carries over, a few words are spelled differently (`=` vs. `<-`), and a handful of words mean something slightly different (`np.std()` vs. `sd()`). Once you know the differences, you can read either one."),
            worked("Counting from zero vs. one",
                   "Suppose you store three scores: 10, 20, 30.",
                   "In **Python**, positions start at 0: `scores[0]` is 10, `scores[1]` is 20, `scores[2]` is 30.",
                   "In **R**, positions start at 1: `scores[1]` is 10, `scores[2]` is 20, `scores[3]` is 30.",
                   "So the same-looking code, `scores[1]`, returns 20 in Python but 10 in R. If a result is off by one position, this is usually why."),
            inWords("Reporting which tools you used",
                    "Name the language, its version, and the packages that did the statistical work: “Models were fit in Python 3.12 with statsmodels 0.14.” Readers can then check that defaults (such as Welch's vs. Student's t-test) match what you intended."),
        ],

        "python-basics": [
            idea("The handful of Python you actually need",
                 "You don't need to become a programmer to do statistics in Python. You need about five ideas: **variables** (names that hold values), **lists** (ordered collections), **functions** (reusable actions such as `round()`), **packages** (collections of functions you import), and **DataFrames** (tables).",
                 "A **variable** is just a label for a value: `n = 40` stores the number 40 under the name `n`. From then on, writing `n` means 40.",
                 "A **DataFrame**, from the pandas package, is a spreadsheet inside Python. Each column is a variable (age, anxiety, region) and each row is one participant. Almost every analysis starts by loading a CSV file into a DataFrame with `pd.read_csv()`.",
                 "Most DataFrame work combines three moves: **select** columns (`df[\"age\"]`), **filter** rows (`df[df[\"age\"] >= 30]`), and **summarize** groups (`df.groupby(\"region\")[\"anxiety\"].mean()`)."),
            analogy("A DataFrame is a spreadsheet you talk to",
                    "In a spreadsheet you'd click a column header, apply a filter, then insert a summary row. In pandas you **type** the same requests: “give me the anxiety column, only for people 30 and over, averaged by region.” The advantage is that the request is saved and can be rerun on new data instantly."),
            worked("Filtering and summarizing by hand",
                   "Imagine a tiny DataFrame with four people: ages 22, 35, 41, 28 and anxiety scores 4.0, 3.5, 5.0, 4.5.",
                   "`df[df[\"age\"] >= 30]` keeps only the rows where age is at least 30: the people aged 35 and 41.",
                   "`[\"anxiety\"].mean()` then averages their anxiety: (3.5 + 5.0) / 2 = **4.25**.",
                   "Put together, `df[df[\"age\"] >= 30][\"anxiety\"].mean()` returns 4.25 — exactly the number you'd get by hand."),
            inWords("Reading code aloud",
                    "A useful habit is to read each line as a sentence: `df.groupby(\"region\")[\"anxiety\"].mean()` reads “take df, group it by region, pick the anxiety column, and compute each group's mean.” If you can say it, you understand it."),
        ],

        "r-basics": [
            idea("How R thinks: everything is a vector",
                 "R's basic building block is the **vector** — an ordered set of values of one type, created with `c()`: `scores <- c(4, 5, 3)`. The arrow `<-` means “store this under that name.”",
                 "Because columns of data are vectors, R applies operations to **all values at once**. `scores * 10` multiplies every score by 10; `mean(scores)` averages them. You rarely need loops.",
                 "Tables of data are **data frames**, and the **tidyverse** packages provide a readable grammar for them: `filter()` keeps rows, `select()` keeps columns, `mutate()` creates columns, `group_by()` + `summarise()` summarizes groups. Steps are chained with the pipe `|>`, which you can read as “and then.”",
                 "One habit to build early: R returns `NA` (missing) if *any* value is missing, unless you add `na.rm = TRUE`. That's deliberate — R makes you decide what to do about missing data."),
            analogy("The pipe is an assembly line",
                    "`survey |> filter(age >= 30) |> summarise(mean(anxiety))` works like an assembly line: the data enter on the left, each station does one job, and the finished product comes out on the right. Reading left to right, you can follow exactly what happened to the data."),
            worked("Vectors in action",
                   "`rt <- c(480, 512, 650, 430)` stores four reaction times.",
                   "`mean(rt)` adds them (480 + 512 + 650 + 430 = 2,072) and divides by 4: **518**.",
                   "`rt > 500` checks each value and returns `FALSE TRUE TRUE FALSE`.",
                   "`rt[rt > 500]` uses those TRUE/FALSE values to keep only the matching ones: **512 650**."),
            inWords("Getting help",
                    "Type `?mean` in R to open the help page for any function. Every help page lists the function's arguments, their defaults, and examples at the bottom — the examples are often the fastest way to learn."),
        ],

        "practice-data": [
            idea("Why practice with made-up data?",
                 "When you analyze real data, you never know the “right answer” — that's why you're doing research. That makes it hard to tell whether a method worked or whether you made a mistake.",
                 "**Simulated data** solves this. You write code that generates data according to rules you choose — for example, “people who use more social media ruminate more, and this effect is weaker for mindful people.” Then you analyze the data as if you didn't know the rules, and check whether your analysis rediscovers them.",
                 "This is exactly how statisticians test new methods, and it's the fastest way to build intuition: you'll see what a real effect looks like in a scatterplot, in a regression table, and in a p-value."),
            analogy("A puzzle with the answer key",
                    "Practicing on simulated data is like doing a crossword that comes with an answer key. You still solve it yourself, but you can check every answer — and when you get one wrong, you learn something specific."),
            worked("What “built-in truth” means",
                   "In the generator, daily wellbeing is created as: *baseline* − 0.25 × (*hours worked that day* − *the person's usual hours*) + *random noise*.",
                   "That −0.25 is the truth: each extra hour above someone's usual lowers wellbeing by a quarter of a point, on average.",
                   "When you later fit a multilevel model to `diary.csv`, the estimate you get should be **close to −0.25** — not exactly, because of the random noise. If you got +0.25, you'd know something went wrong."),
            inWords("How simulated data appear in papers",
                    "Researchers often include a simulation in a preregistration or appendix: “We simulated 1,000 datasets under the hypothesized effect (b = −0.25) to confirm the planned model recovers it and to estimate power.” You'll learn to do exactly this in *Planning sample size*."),
        ],

        "reading-output": [
            idea("A regression table is a list of answers to the same question",
                 "Every row of a regression table answers one question about one predictor: **“How much does the outcome change when this predictor goes up by one unit, holding the others constant — and how sure are we?”**",
                 "The **coefficient** (estimate) is the answer: the size and direction of the change. The **standard error** says how much that estimate would bounce around if you repeated the study with new people. The **t value** is the estimate divided by its standard error — how many standard errors the estimate is from zero. The **p-value** turns that into a probability, and the **confidence interval** gives a plausible range for the true value.",
                 "Below the rows, **R²** tells you how much of the variation in the outcome the model explains overall, and the **number of observations** tells you how many rows were actually used — always check it, because rows with missing values are dropped silently."),
            analogy("Weather forecasts",
                    "A coefficient is like a forecast of “2 cm of rain,” and its confidence interval is “between 1 and 3 cm.” A forecast with a narrow range is more useful than one that says “between 0 and 10 cm,” even if both have the same middle value. Always read the estimate *and* its uncertainty together."),
            worked("Reading one row",
                   "Suppose the row for rumination reads: estimate **0.45**, standard error **0.05**, t **9.0**, p **< .001**, 95% CI **[0.35, 0.55]**.",
                   "Estimate: each one-point increase in rumination predicts 0.45 points more anxiety.",
                   "t = 0.45 / 0.05 = 9 — the estimate is nine standard errors away from zero, which would be extraordinarily unlikely if there were truly no relationship. Hence p < .001.",
                   "CI: the true slope is plausibly anywhere from 0.35 to 0.55. Because the whole interval is above zero, the relationship is positive."),
            inWords("Turning a row into a sentence",
                    "“Rumination positively predicted anxiety, *b* = 0.45, 95% CI [0.35, 0.55], *t*(372) = 9.0, *p* < .001.” The degrees of freedom (372) come from the residual df line of the output."),
        ],

        // MARK: Unit 1 · Foundations

        "why-statistics": [
            idea("Statistics is the science of learning from variable data",
                 "People differ. Two participants in the same condition give different answers; the same person gives different answers on different days. That **variability** is why we can't just look at one person and draw conclusions.",
                 "Statistics gives us tools to answer three kinds of questions despite that variability: **describing** (what does the data look like?), **estimating** (what's the likely size of an effect in the wider population?), and **testing** (could this pattern plausibly be just chance?).",
                 "Before any of that, a study needs a clear question and clear **variables**. The **independent variable (IV)** is what you think causes or explains differences — a teaching method, a sentence type, a person's age. The **dependent variable (DV)** is what you measure as the outcome — a test score, a reaction time, a rating.",
                 "Finally, the **design** determines what you can conclude. In an **experiment**, the researcher randomly assigns the IV, so groups differ only by chance apart from the manipulation — differences in the DV can be attributed to it. In an **observational** study, you measure things as they are, so any association might be caused by something else (a **confounder**)."),
            analogy("Hearing a signal through static",
                    "Imagine trying to hear a radio station through static. The station is the effect you care about; the static is the natural variability between people. Statistics is the set of techniques for deciding whether you really hear the station — and how loud it is — rather than imagining a tune in the noise. More listeners (a bigger sample) and a quieter room (more precise measures) both make the signal easier to detect."),
            worked("Why random assignment matters",
                   "A school compares two teaching methods. In Version A, teachers *choose* which method to use; in Version B, classes are *randomly assigned*.",
                   "Version A: the active-learning classes score 5 points higher. But perhaps more motivated teachers chose active learning, and motivation — not the method — raised scores. We can't tell.",
                   "Version B: randomization means motivated and unmotivated teachers are spread roughly evenly across both methods. If active-learning classes still score 5 points higher, the method is the most plausible explanation."),
            inWords("Matching claims to designs",
                    "From an experiment: “Active learning **increased** test scores.” From an observational study: “Active learning was **associated with** higher test scores.” The verb you choose tells readers what kind of evidence you have."),
        ],

        "measurement": [
            idea("Not all numbers are created equal",
                 "Data often arrive as numbers, but the numbers can mean very different things. The **level of measurement** describes what the numbers can tell you, and it determines which statistics make sense.",
                 "**Nominal** variables are labels: native language, region, experimental condition. Even if they're coded 1, 2, 3, the numbers have no order — averaging them is meaningless.",
                 "**Ordinal** variables have a meaningful order but unknown spacing: education level (high school < bachelor's < master's), or a single “strongly disagree … strongly agree” item. You know 4 is more than 3, but not that the gap from 3 to 4 equals the gap from 4 to 5.",
                 "**Interval** variables have equal spacing but no true zero (temperature in °C; many standardized scores). **Ratio** variables have equal spacing *and* a true zero, so ratios make sense: a 600 ms reaction time really is twice as long as 300 ms.",
                 "In practice, the biggest decision is how to treat rating scales. A **single** Likert item is ordinal. The **average of many items** measuring the same thing is usually treated as roughly interval. You'll see in Unit 9 that there are models designed for ordinal outcomes when that assumption is doubtful."),
            analogy("Race results",
                    "Runners' **bib numbers** are nominal — just labels. Their **finishing places** (1st, 2nd, 3rd) are ordinal — ordered, but 1st and 2nd might be a second apart while 2nd and 3rd are a minute apart. Their **finishing times** are ratio — equal units with a true zero, so you can say one runner took 10% longer than another."),
            worked("What goes wrong when codes are treated as numbers",
                   "Suppose region is coded 1 = urban, 2 = suburban, 3 = rural, and you put that number straight into a regression.",
                   "The model assumes suburban is exactly “halfway” between urban and rural, and that moving from 1 to 2 has the same effect as moving from 2 to 3. Neither is a meaningful assumption.",
                   "Declaring region as a **category** (`astype(\"category\")` / `factor()`) instead makes the model estimate a separate difference for each region compared with a reference region."),
            inWords("Describing measures in a methods section",
                    "“Anxiety was measured with a 10-item scale (1 = *not at all*, 5 = *extremely*); item responses were averaged, and the mean score was treated as continuous.” Saying how you treated the scale lets readers judge your choice."),
        ],

        "toolkit": [
            idea("Packages: other people's expertise, one install away",
                 "Neither Python nor R does advanced statistics out of the box. Instead, experts write **packages** — bundles of tested functions — and share them for free. You **install** a package once on your computer, then **load** it at the top of each script.",
                 "A small set of packages covers most of this course: **pandas** / **tidyverse** for handling data tables; **SciPy** / base R for classic tests; **statsmodels** / `lm()` and `glm()` for regression; **pingouin** / **effectsize** for research-friendly output; **seaborn** / **ggplot2** for figures; and **lme4**, **lavaan**, and **psych** in R for mixed models, mediation, and measurement.",
                 "Both languages share a **formula language** for models: `outcome ~ predictor1 + predictor2`. The variable to the left of `~` is what you're predicting; the variables on the right are what you're using to predict it. Learning this once pays off across t-tests, ANOVA, regression, and mixed models."),
            analogy("Apps on a phone",
                    "A new phone can make calls, but you install apps for maps or banking. Packages are the apps of Python and R. Installing (`pip install`, `install.packages()`) downloads the app; loading (`import`, `library()`) opens it for this session."),
            worked("Reading a formula",
                   "`wellbeing ~ income + age` means “predict wellbeing from income and age.”",
                   "`wellbeing ~ income * age` means “predict wellbeing from income, age, **and** their interaction” — whether the effect of income depends on age. The `*` is shorthand for `income + age + income:age`.",
                   "`rt ~ condition + (1 | participant)` (in R's lme4) adds a random intercept for each participant — you'll meet this in Unit 7."),
            inWords("Citing software",
                    "Cite the packages that did the statistical work, with versions: “Mixed models were estimated with lme4 1.1-35 (Bates et al., 2015).” Most packages print their citation with `citation(\"lme4\")` in R."),
        ],

        "tidy-data": [
            idea("Good analyses start with well-shaped data",
                 "Raw data rarely arrive ready to analyze. Survey platforms add extra header rows, experiment software writes one file per participant, and variables come in odd formats. **Data cleaning** — often half the work of a project — turns that into a single, consistent table.",
                 "The target shape is **tidy data**: each **row** is one observation, each **column** is one variable, and each **cell** holds one value. What counts as “one observation” depends on the question: one participant for a survey, one participant × trial for a reaction-time experiment.",
                 "Repeated measures can be stored **wide** (one row per person, a column for each condition or time) or **long** (one row per person × condition). Wide is easy to read; long is what most models — especially mixed models — need. Converting between them is called **reshaping** (`melt` / `pivot_longer`, `pivot` / `pivot_wider`).",
                 "Cleaning also involves **exclusions**: removing participants who failed attention checks, or trials that are impossibly fast. These choices can change results, so decide the rules **before** you see the outcomes and report them all."),
            analogy("A filing system",
                    "Wide data is like a filing cabinet with one folder per person, holding a single sheet with all their scores. Long data is like a card index with one card per score, each card labeled with the person and condition. The card index is easier to sort, count, and model — which is why analysis software prefers it."),
            worked("Wide to long",
                   "Wide: one row per student — student 1: pretest 60, posttest 66; student 2: pretest 72, posttest 75.",
                   "Long: four rows — (1, pre, 60), (1, post, 66), (2, pre, 72), (2, post, 75).",
                   "Same information, different shape. Two students × two times = four rows. With 150 students you'd get 300 rows."),
            inWords("Reporting data cleaning",
                    "“Of 412 respondents, 37 were excluded (29 failed the attention check; 8 completed the survey in under 3 minutes), leaving 375 for analysis. Exclusion rules were preregistered.”"),
        ],

        // MARK: Unit 2 · Describing data

        "central-tendency": [
            idea("Two questions about any variable: where's the middle, and how spread out?",
                 "Before testing anything, describe your data. The first question is **central tendency**: what's a typical value? The second is **spread** (variability): how different are people from each other?",
                 "The **mean** adds all values and divides by how many there are. It uses every value, which makes it efficient — but also sensitive to extreme values. The **median** is the middle value when you line everyone up in order; half the values are below it and half above. It ignores how extreme the extremes are, so it's **robust** to outliers and skew.",
                 "For spread, the **standard deviation (SD)** is roughly the typical distance of a value from the mean. A small SD means people are similar; a large SD means they vary a lot. The **interquartile range (IQR)** is the spread of the middle 50% (the 75th minus the 25th percentile) and, like the median, is robust.",
                 "Which to report? For roughly symmetric data, the mean and SD. For skewed data — incomes, reaction times, counts — the median and IQR are usually more honest, or report both."),
            analogy("Average income in a room",
                    "Ten people in a café each earn about $50,000. The mean and median are both about $50,000. Then a billionaire walks in. The **mean** income jumps to over $90 million — a number that describes nobody in the room. The **median** barely moves. That's why governments report median household income."),
            worked("Computing the mean, median, and SD",
                   "Five reaction times (ms): 400, 420, 450, 480, 750.",
                   "**Mean** = (400 + 420 + 450 + 480 + 750) / 5 = 2,500 / 5 = **500 ms**.",
                   "**Median**: sorted, the middle (3rd) value is **450 ms** — lower than the mean, because the slow 750 ms response pulls the mean up.",
                   "**SD**: deviations from the mean are −100, −80, −50, −20, +250; squared: 10,000, 6,400, 2,500, 400, 62,500; sum = 81,800; divide by n − 1 = 4 → 20,450; square root ≈ **143 ms**."),
            inWords("Reporting descriptives",
                    "“Reaction times were right-skewed (*Mdn* = 450 ms, IQR = 420–480); the mean was 500 ms (*SD* = 143).” Every group in every study should get at least its *n*, a measure of center, and a measure of spread."),
        ],

        "visualizing": [
            idea("Always look before you calculate",
                 "Summary statistics compress hundreds of numbers into a few. That's useful, but it hides things: two groups can share a mean and SD yet have completely different shapes. A plot shows the **shape** of the data — where values cluster, whether there's a long tail, whether there are outliers or impossible values, and whether there are two clusters instead of one.",
                 "A **histogram** divides the range of a variable into bins and draws a bar for how many values fall in each. It's the best way to see the shape of one variable. A **boxplot** summarizes a variable with five numbers — the median (line), the 25th and 75th percentiles (box), and whiskers reaching toward the extremes — and is good for comparing several groups side by side.",
                 "Whenever you can, show the **raw data points** too (jittered, so they don't overlap). They reveal the sample size and any clusters that a box or bar would hide."),
            analogy("Anscombe's famous lesson",
                    "In 1973 the statistician Francis Anscombe created four small datasets with the same means, SDs, correlations, and regression lines. Plotted, one is a neat straight line, one is a curve, one is a line with a single outlier, and one is a vertical stack of points plus one far-off point. Identical numbers, four different stories — which is why plotting comes first."),
            worked("Reading a boxplot",
                   "A boxplot of test scores has its box from 58 to 70 and a line at 64, whiskers from 47 to 82, and one dot at 95.",
                   "Median = **64**: half the students scored below 64.",
                   "IQR = 70 − 58 = **12**: the middle half of students span 12 points.",
                   "The dot at 95 lies beyond 1.5 × IQR above the box (70 + 18 = 88), so it's flagged as a **potential outlier** — worth checking, not automatically deleting."),
            inWords("Describing a distribution in words",
                    "“Scores were roughly symmetric and unimodal, with one high outlier (95) that was retained after verification.” Describe **shape, center, spread, and unusual values**."),
        ],

        "normal-distribution": [
            idea("The bell curve and why it shows up everywhere",
                 "Many variables — heights, measurement errors, averages of many items — have a similar shape: most values near the middle, fewer and fewer toward the extremes, symmetric on both sides. That bell shape is the **normal distribution**.",
                 "A normal distribution is completely described by two numbers: its **mean** (where the peak is) and its **standard deviation** (how wide it is). In any normal distribution, about **68%** of values are within 1 SD of the mean, **95%** within about 2 SD (1.96, to be exact), and **99.7%** within 3 SD.",
                 "A **z-score** re-expresses any value as “how many SDs from the mean”: z = (value − mean) / SD. A z of 0 is exactly average; +1 is one SD above; −2 is two SDs below. Because z-scores have no units, they let you compare scores from different scales.",
                 "Why does the normal distribution matter so much? Even when raw data aren't normal, **averages** of many observations tend to be (the Central Limit Theorem, next unit). Many tests rely on that fact."),
            analogy("A Galton board",
                    "Drop many balls through rows of pegs: at each peg a ball bounces left or right at random. Most balls end up near the middle because left and right bounces mostly cancel out; only a few bounce the same way every time and land at the edges. The pile at the bottom is a bell curve. Any outcome built from many small, independent random pushes tends to look like this."),
            worked("Using z-scores",
                   "Exam scores have mean 70 and SD 8. A student scores 82.",
                   "z = (82 − 70) / 8 = **1.5** — one and a half SDs above average.",
                   "In a normal distribution, about 93% of values are below z = 1.5, so this student is around the **93rd percentile**.",
                   "A second student, on a different test with mean 50 and SD 5, scores 60: z = (60 − 50) / 5 = **2.0**. Relative to their classmates, the second student did better."),
            inWords("Reporting standardized scores",
                    "“Scores were standardized within each test (z-scores) before being combined.” When you transform a skewed variable instead, say so: “Reaction times were log-transformed to reduce right skew.”"),
        ],

        // MARK: Unit 3 · Inference

        "standard-error": [
            idea("From your sample to everyone else",
                 "You study a **sample** (say, 100 students) but want to say something about a **population** (all students like them). The sample mean is your best guess for the population mean — but a different sample of 100 would give a slightly different mean. The question is **how much** sample means bounce around.",
                 "Imagine repeating your study many times. The collection of all those sample means is called the **sampling distribution**. Its standard deviation has a special name: the **standard error (SE)**. For a mean, SE = SD / √n. The SD describes how much **individuals** vary; the SE describes how much **sample means** vary.",
                 "Notice the √n: larger samples give smaller standard errors, because individual quirks average out. Quadrupling the sample size halves the SE.",
                 "A **confidence interval** uses the SE to give a plausible range for the population value: roughly the estimate ± 2 SE for 95% confidence. The interpretation is about the method: if you ran the study many times and built an interval each time, about 95% of those intervals would contain the true value."),
            analogy("Tasting soup",
                    "To check whether a big pot of soup is salty enough, you taste one spoonful. A single spoonful might be unusually salty or bland. Stir well and taste a bigger spoonful, and your judgment becomes more reliable. The standard error is how far off your spoonful is likely to be — and a bigger (or better-stirred) spoonful shrinks it."),
            worked("Computing an SE and a 95% CI",
                   "A sample of n = 36 people has mean anxiety 4.2 and SD 1.2.",
                   "SE = 1.2 / √36 = 1.2 / 6 = **0.20**.",
                   "95% CI ≈ 4.2 ± 2 × 0.20 = **[3.8, 4.6]**. (The exact multiplier from the t distribution with 35 df is 2.03, giving [3.79, 4.61].)",
                   "With n = 144 instead, SE = 1.2 / 12 = 0.10, and the CI shrinks to about [4.0, 4.4] — four times the data, half the width."),
            inWords("Reporting estimates with uncertainty",
                    "“Mean anxiety was 4.2 (95% CI [3.8, 4.6]).” Always pair an estimate with its CI — a bare mean says nothing about how precisely you know it."),
        ],

        "hypothesis-testing": [
            idea("A structured way to ask “could this just be chance?”",
                 "Suppose a new teaching method group scores 5 points higher than a control group. That could be a real effect — or the luck of who ended up in which group. A **hypothesis test** asks: **if there were truly no effect, how surprising would a difference this large be?**",
                 "You start with a skeptical default, the **null hypothesis (H₀)**: “there's no difference.” The **alternative hypothesis (Hₐ)** is that there is one. You then compute a **test statistic** — usually the observed effect divided by its standard error — and from it a **p-value**: the probability of getting a result at least this extreme **if H₀ were true**.",
                 "A small p-value (conventionally below **α = .05**) means the data would be surprising under H₀, so you **reject** H₀. A large p-value means the data are compatible with H₀ — not that H₀ is true. Absence of evidence isn't evidence of absence.",
                 "Two kinds of mistakes are possible. A **Type I error** (false positive) is rejecting a true H₀; α controls how often that happens. A **Type II error** (false negative) is missing a real effect; reducing it requires enough data (power, later in this unit)."),
            analogy("A criminal trial",
                    "A defendant is presumed innocent (H₀) until the evidence is strong enough to convict beyond reasonable doubt (p < α). A “not guilty” verdict doesn't prove innocence — it means the evidence wasn't strong enough. Convicting an innocent person is a Type I error; letting a guilty one go is a Type II error. Requiring very strong evidence protects against the first at the cost of more of the second."),
            worked("A coin-flipping test",
                   "You suspect a coin is biased toward heads, so you flip it 10 times and get 9 heads.",
                   "H₀: the coin is fair (p = .5). How likely are 9 or more heads out of 10 if it's fair? 9 heads: 10 ways; 10 heads: 1 way; out of 2¹⁰ = 1,024 equally likely sequences. So p = 11 / 1,024 ≈ **.011** for “9 or more heads” (one-sided).",
                   "That's below .05, so you'd reject the idea that the coin is fair. With only 7 heads, p ≈ .17 — not surprising enough to reject H₀, even though 7 is more than 5."),
            inWords("What a p-value lets you say — and doesn't",
                    "Correct: “If there were no true difference, a difference this large would occur about 3% of the time (*p* = .03).” Incorrect: “There's a 97% chance the effect is real” or “there's a 3% chance the result is due to chance.” Always report the effect size and CI alongside *p*."),
        ],

        "bootstrap": [
            idea("Let the data estimate their own uncertainty",
                 "To build a confidence interval you need to know how much a statistic would vary from sample to sample. For a mean there's a formula (SE = SD / √n). For many statistics — a median, a ratio, the product of two regression coefficients — there's no simple formula.",
                 "The **bootstrap** gets around this with computer power. Treat your sample as a miniature version of the population. Draw a new sample of the same size **from your own data, with replacement** (so some people appear twice and others not at all), compute the statistic, and repeat thousands of times. The spread of those thousands of values approximates the sampling distribution.",
                 "The middle 95% of the bootstrap values gives a **percentile confidence interval**: the 2.5th percentile is the lower bound and the 97.5th the upper bound.",
                 "One crucial rule: **resample whatever was sampled independently**. If each person contributed many observations (days, trials), resample **people** and keep each person's observations together — a **cluster bootstrap**. Resampling individual observations would pretend you had far more independent information than you do."),
            analogy("Pulling yourself up by your bootstraps",
                    "The name comes from the idea of lifting yourself up by your own bootstraps — getting something seemingly impossible from what you already have. You don't have access to the population, but your sample is your best picture of it, so you “resample the population” by resampling the sample."),
            worked("A tiny bootstrap by hand",
                   "Sample of five values: 2, 4, 5, 7, 12. Sample median = 5.",
                   "Resample 1 (with replacement): 4, 4, 7, 12, 2 → sorted 2, 4, 4, 7, 12 → median **4**.",
                   "Resample 2: 5, 12, 12, 7, 5 → median **7**. Resample 3: 2, 2, 5, 4, 7 → median **4**.",
                   "Repeat 10,000 times and sort the 10,000 medians. If the 250th is 4 and the 9,750th is 7, the 95% bootstrap CI for the median is **[4, 7]**. (With only five values the interval is crude — the bootstrap works best with moderate to large samples.)"),
            inWords("Reporting a bootstrap CI",
                    "“The median difference was 0.4 points (95% percentile bootstrap CI [0.1, 0.8], 10,000 resamples). Because participants contributed multiple days, we resampled participants rather than days.”"),
        ],

        "effect-sizes": [
            idea("Significance says “whether”; effect size says “how much”",
                 "With a big enough sample, even a tiny, unimportant difference becomes statistically significant. With a small sample, an important difference can fail to reach significance. So a p-value alone can't tell you whether an effect **matters**. That's the job of an **effect size**.",
                 "**Cohen's d** expresses a difference between two means in standard deviation units: d = (mean₁ − mean₂) / SD. A d of 0.5 means the groups differ by half an SD. Rough benchmarks are 0.2 small, 0.5 medium, 0.8 large — but what counts as meaningful depends on the field.",
                 "Other effect sizes fit other analyses: **r** for correlations, **η²** (eta squared) for the share of variance explained in ANOVA, **odds ratios** for binary outcomes.",
                 "**Power** is the probability that a study will detect an effect **if it really exists**. It depends on the true effect size, the sample size, and α. Researchers aim for at least 80% power, and plan sample sizes before collecting data to get there."),
            analogy("Hearing a whisper vs. a shout",
                    "A large effect is a shout — you'll hear it even in a noisy room with few listeners. A small effect is a whisper — you need a quiet room and many careful listeners to be confident you heard it. Power analysis asks: given how loud we expect the effect to be, how many listeners do we need?"),
            worked("Computing d",
                   "Active-learning students average 70 on a test; lecture students average 64. Both groups have an SD of about 10.",
                   "d = (70 − 64) / 10 = **0.6** — a medium-to-large effect: the average active-learning student scores higher than about 73% of lecture students.",
                   "To detect d = 0.6 with 80% power at α = .05, you'd need about **45 students per group**. For d = 0.3, you'd need about **176 per group** — halving the effect quadruples the sample needed."),
            inWords("Reporting effect sizes",
                    "“Active-learning students scored higher than lecture students, *t*(98) = 3.0, *p* = .003, *d* = 0.60, 95% CI [0.20, 1.00].” Include the CI around *d*: with small samples it's often wide."),
        ],

        "sample-planning": [
            idea("Decide how much data you need before you collect it",
                 "Running a study that's too small wastes everyone's time: real effects are likely to be missed, and the ones that do reach significance tend to be exaggerated. Running one that's far too large wastes resources. **Sample size planning** finds the middle ground.",
                 "For simple designs, power formulas (built into `pwr` in R or `statsmodels` in Python) give the answer directly. For anything more complex — covariates, interactions, clustered data — **simulation** is easier and more honest: write code that generates fake data with the effect you expect, run your planned analysis on it, repeat 1,000 times, and count how often the result is significant. That share is your power.",
                 "Sometimes researchers want to **look at the data early** (an interim analysis) and stop if the evidence is already overwhelming. Doing that naively — testing at p < .05 each time you look — inflates false positives, because every look is another chance for noise to cross the line. **Sequential designs** fix this by using stricter thresholds at each look, planned in advance, so the overall error rate stays at 5%."),
            analogy("Packing for a trip",
                    "Before a hike you estimate how much water you'll need from the distance, the heat, and your pace. Bring too little and you fail halfway; bring far too much and you're carrying dead weight. Sample size planning is the same calculation: from the expected effect, the noise, and your design, estimate how much data will get you to a clear answer."),
            worked("Why peeking inflates errors",
                   "Suppose there's truly no effect and you test once at the end: a 5% chance of a false positive.",
                   "Now you test halfway **and** at the end, each at p < .05. You get two chances to be fooled. Simulations show the overall false-positive rate rises to about **8%**.",
                   "An O'Brien–Fleming plan instead tests at p < .005 halfway and p < .048 at the end. The early bar is very high, so most of the 5% is “saved” for the final analysis, and the overall rate stays at **5%**."),
            inWords("Reporting a sample size justification",
                    "“A simulation with 1,000 datasets indicated that 50 students per method would give 80% power to detect a 0.4 SD difference in an ANCOVA adjusting for the pre-test (*r* = .7), at α = .05.”"),
        ],
    ]
}
