import Foundation

/// Shorthand for a multiple-choice question.
private func q(_ prompt: String, _ options: [String], _ answer: Int, _ explanation: String) -> Question {
    Question(prompt: prompt, options: options, answer: answer, explanation: explanation)
}

extension Lesson {
    /// The lesson's own questions followed by the extra question bank for it.
    var allQuestions: [Question] {
        quiz + (Curriculum.extraQuestions[id] ?? [])
    }
}

/// Additional "Check your understanding" questions, keyed by lesson ID.
extension Curriculum {
    static let extraQuestions: [String: [Question]] = extraQuestionsBasics
        .merging(extraQuestionsCore) { $0 + $1 }
        .merging(extraQuestionsResearch) { $0 + $1 }
        .merging(extraQuestionsStructure) { $0 + $1 }
        .merging(extraQuestionsVisualsAndLabs) { $0 + $1 }

    // MARK: Units 0–2

    private static let extraQuestionsBasics: [String: [Question]] = [
        "vs-code": [
            q("With the R extension, which shortcut runs the current line or selection?",
              ["Cmd/Ctrl + Enter", "Shift + Tab", "Cmd/Ctrl + S", "F1"], 0,
              "Cmd/Ctrl + Enter sends code to the R terminal; Cmd/Ctrl + Shift + S sources the whole file."),
            q("What is a Python virtual environment for?",
              ["Making Python faster", "Keeping each project's packages separate", "Running R code", "Backing up files"], 1,
              "Each project gets its own package versions, so updating one project can't break another."),
            q("Where do you install Python packages such as pandas?",
              ["Inside R", "In the terminal with pip, with the virtual environment active", "In VS Code's Extensions panel", "In a CSV file"], 1,
              "Extensions add editor features; packages are installed into the interpreter with pip."),
        ],
        "python-vs-r": [
            q("Which of these is R's native pipe?",
              ["|>", "->", "%%", "::"], 0,
              "`|>` passes the left-hand result into the next function. (`%>%` is the older magrittr pipe.)"),
            q("By default, pandas `.mean()` treats missing values by…",
              ["Returning NaN", "Skipping them", "Treating them as 0", "Raising an error"], 1,
              "pandas skips NaN by default; R's `mean()` returns NA unless `na.rm = TRUE`."),
            q("You set seed 42 in both Python and R and simulate data. The numbers will be…",
              ["Identical", "Different", "Identical for integers only", "An error"], 1,
              "The two languages use different random-number generators."),
        ],
        "python-basics": [
            q("What does `scores[-1]` return for `scores = [4, 5, 3]`?",
              ["4", "3", "An error", "−1"], 1,
              "Negative indices count from the end; −1 is the last element."),
            q("`df[[\"age\", \"anxiety\"]]` returns…",
              ["A Series", "A DataFrame with two columns", "A single number", "A list"], 1,
              "Double brackets select a list of columns, which is a DataFrame."),
            q("Which operator combines two row conditions with “and” in pandas?",
              ["and", "&&", "&", "+"], 2,
              "Use `&` (and `|` for or), with each condition in parentheses."),
            q("What does `len(df)` return for a DataFrame?",
              ["Number of columns", "Number of rows", "Number of cells", "Number of missing values"], 1,
              "`len()` counts rows; `df.shape` gives (rows, columns)."),
        ],
        "r-basics": [
            q("`c(1, 2, 3) * 2` returns…",
              ["2 4 6", "1 2 3 1 2 3", "12", "An error"], 0,
              "Arithmetic on a vector applies to every element."),
            q("What does `library(tidyverse)` do?",
              ["Installs the package", "Loads an installed package for this session", "Updates R", "Opens the help page"], 1,
              "Install once with `install.packages()`; load every session with `library()`."),
            q("`mean(c(1, NA, 3))` returns…",
              ["2", "NA", "1.33", "An error"], 1,
              "Any NA makes the result NA unless you add `na.rm = TRUE`."),
            q("Which selects the column `age` from data frame `df`?",
              ["df.age", "df$age", "df[age]", "age(df)"], 1,
              "`$` extracts a single column; `df[[\"age\"]]` also works."),
        ],
        "practice-data": [
            q("How many rows does each person contribute to diary.csv?",
              ["1", "7", "14", "100"], 2,
              "Each of the 100 people reports on 14 days."),
            q("In classroom.csv, what is the built-in effect of active learning?",
              ["It lowers scores", "It raises post-test scores about 0.4 SD above lecture", "No effect", "It only changes the pre-test"], 1,
              "Active learning has a +0.40 SD effect; flipped only +0.10."),
            q("In essays.csv, how do the two raters differ?",
              ["They never agree", "Rater B scores slightly higher on average", "Rater A is random", "They rate different essays"], 1,
              "Rater B is about 0.3 points more lenient — a systematic difference that matters for absolute-agreement ICCs."),
        ],
        "reading-output": [
            q("How is p = .0004 reported in APA style?",
              ["p = .0004", "p < .001", "p = 0.000", "p ≈ 0"], 1,
              "Values below .001 are reported as p < .001."),
            q("Why is adjusted R² lower than R²?",
              ["It's a rounding error", "It penalizes the number of predictors", "It uses fewer rows", "It ignores the intercept"], 1,
              "Adding predictors always raises R²; adjusted R² only rises if they help enough."),
            q("A coefficient's 95% CI is [−0.05, 0.31]. At α = .05 it is…",
              ["Significant", "Not significant, because the CI includes 0", "Negative", "Equal to R²"], 1,
              "A 95% CI that contains 0 corresponds to p > .05."),
        ],
        "why-statistics": [
            q("Operationalizing “loneliness” means…",
              ["Looking it up in a dictionary", "Choosing a concrete measure, such as a validated scale score", "Removing it from the study", "Correlating it with something"], 1,
              "Operationalization turns a construct into something you can measure."),
            q("Ice-cream sales and drownings are correlated. The most plausible explanation is…",
              ["Ice cream causes drowning", "A third variable — hot weather — drives both", "Drowning causes ice-cream sales", "Pure coincidence"], 1,
              "A confound affects both variables."),
            q("A researcher can't randomly assign people's native language. The study is therefore…",
              ["Experimental", "Observational (quasi-experimental)", "Invalid", "Qualitative"], 1,
              "Without random assignment, groups may differ in other ways too."),
        ],
        "measurement": [
            q("Education coded HS < BA < MA < PhD is…",
              ["Nominal", "Ordinal", "Interval", "Ratio"], 1,
              "Ordered categories with unequal gaps."),
            q("The number of words a participant produces is…",
              ["Nominal", "Ordinal", "Interval", "Ratio"], 3,
              "Counts have a true zero and equal units."),
            q("Temperature in °C is…",
              ["Nominal", "Ordinal", "Interval", "Ratio"], 2,
              "Equal gaps, but 0 °C isn't “no temperature”, so ratios aren't meaningful."),
        ],
        "toolkit": [
            q("Which R package is the standard for mixed-effects models?",
              ["ggplot2", "lme4", "dplyr", "psych"], 1,
              "lme4 provides `lmer()` and `glmer()`."),
            q("In Python, formula-based regression comes from…",
              ["numpy", "statsmodels.formula.api", "matplotlib", "os"], 1,
              "`smf.ols(\"y ~ x\", data=df)` uses R-style formulas."),
            q("Why record package versions?",
              ["To reduce file size", "Results can change between versions, so others need them to reproduce your work", "Python requires it", "It makes code faster"], 1,
              "Defaults and algorithms sometimes change across versions."),
        ],
        "tidy-data": [
            q("Tidy data means…",
              ["One row per observation, one column per variable", "One sheet per participant", "Wide format always", "No missing values"], 0,
              "That structure is what modeling functions expect."),
            q("R's `pivot_longer()` corresponds to which pandas method?",
              ["pivot", "melt", "merge", "concat"], 1,
              "Both go from wide to long."),
            q("Choosing outlier rules after seeing which one gives p < .05 is an example of…",
              ["Preregistration", "A researcher degree of freedom", "A robustness check", "A power analysis"], 1,
              "Data-dependent choices inflate false-positive rates."),
        ],
        "central-tendency": [
            q("What is the mean of 2, 3, 3, 10?",
              ["3", "4.5", "3.5", "10"], 1,
              "(2 + 3 + 3 + 10) / 4 = 4.5."),
            q("What is the median of 2, 3, 3, 10?",
              ["3", "4.5", "2.5", "6.5"], 0,
              "The middle two values are 3 and 3."),
            q("Which statistic is most affected by a single extreme outlier?",
              ["Median", "IQR", "Mean", "Mode"], 2,
              "The mean uses every value's magnitude."),
        ],
        "visualizing": [
            q("Which plot best shows the distribution of one continuous variable?",
              ["Pie chart", "Histogram or density plot", "Line chart", "A table of means"], 1,
              "Histograms show shape, spread, and outliers."),
            q("The box in a boxplot spans…",
              ["Minimum to maximum", "The interquartile range (25th–75th percentile)", "Mean ± 1 SD", "The 95% CI"], 1,
              "The line inside is the median."),
            q("A ceiling effect means…",
              ["Scores bunch at the top of the scale", "Scores are normally distributed", "The axis is truncated", "There are no outliers"], 0,
              "It can hide real differences between groups."),
        ],
        "normal-distribution": [
            q("x = 115 on a scale with M = 100 and SD = 15. What is z?",
              ["1", "1.5", "15", "0.15"], 0,
              "(115 − 100) / 15 = 1."),
            q("About what percentage of a normal distribution lies within ±1 SD?",
              ["50%", "68%", "95%", "99.7%"], 1,
              "The 68–95–99.7 rule."),
            q("In a Q–Q plot, points bend upward above the line at the right end. This suggests…",
              ["A long right tail (right skew)", "Left skew", "Perfect normality", "Too few observations"], 0,
              "The largest values are bigger than a normal distribution predicts."),
        ],
    ]

    // MARK: Units 3–6

    private static let extraQuestionsCore: [String: [Question]] = [
        "standard-error": [
            q("SD = 20 and n = 100. What is the standard error of the mean?",
              ["0.2", "2", "20", "200"], 1,
              "20 / √100 = 2."),
            q("A confidence interval gets wider when…",
              ["n increases", "You move from 95% to 99% confidence", "The SD decreases", "Never"], 1,
              "More confidence requires a wider interval."),
            q("A poll's “± 3 points” margin of error is…",
              ["The SD of responses", "The half-width of a 95% CI", "The p-value", "The response rate"], 1,
              "It's the uncertainty from sampling."),
        ],
        "hypothesis-testing": [
            q("If H₀ is true and α = .05, how often will you get p < .05?",
              ["Never", "About 5% of the time", "About 50% of the time", "About 95% of the time"], 1,
              "That's what α means: the false-positive rate when H₀ is true."),
            q("p = .20 means…",
              ["H₀ is true", "The data aren't unusual under H₀ — insufficient evidence against it", "The effect is 20%", "There's an 80% chance the effect is real"], 1,
              "Failing to reject H₀ isn't evidence that it's true."),
            q("You run 10 independent tests at α = .05 and every null is true. The chance of at least one false positive is about…",
              ["5%", "40%", "50%", "100%"], 1,
              "1 − .95¹⁰ ≈ .40."),
        ],
        "effect-sizes": [
            q("Means are 105 and 100 with a pooled SD of 10. Cohen's d is…",
              ["0.05", "0.5", "5", "50"], 1,
              "(105 − 100) / 10 = 0.5."),
            q("Power increases when…",
              ["n decreases", "The true effect is larger", "α decreases", "Measurement gets noisier"], 1,
              "Bigger effects are easier to detect."),
            q("Significant results from underpowered studies tend to…",
              ["Underestimate the effect", "Overestimate the effect", "Estimate it correctly", "Have no effect size"], 1,
              "Only overestimates cross the significance threshold — the winner's curse."),
        ],
        "t-tests": [
            q("Welch's t-test differs from Student's t-test because it…",
              ["Doesn't assume equal variances", "Requires paired data", "Uses ranks", "Is one-tailed"], 0,
              "It adjusts the df for unequal variances."),
            q("Is participants' accuracy different from 50% chance? Which test?",
              ["One-sample t-test", "Paired t-test", "Independent t-test", "Chi-square"], 0,
              "Compare one mean with a fixed value."),
            q("A paired t-test is equivalent to…",
              ["A one-sample t-test on the difference scores", "An independent t-test", "A correlation", "A chi-square"], 0,
              "It tests whether the mean difference is 0."),
        ],
        "anova": [
            q("The F ratio compares…",
              ["Between-group variance to within-group variance", "Two means", "Medians", "Correlations"], 0,
              "Large F = groups differ more than chance would suggest."),
            q("With 3 groups, how many pairwise comparisons are there?",
              ["2", "3", "6", "9"], 1,
              "A–B, A–C, B–C."),
            q("η²ₚ = .06 means the factor explains about…",
              ["6% of the variance (after removing other effects)", "60% of the variance", "6 points of difference", "A p-value of .06"], 0,
              "Partial η² is a proportion of variance."),
        ],
        "chi-square": [
            q("How many degrees of freedom does a 3 × 4 contingency table have?",
              ["6", "7", "11", "12"], 0,
              "(rows − 1) × (columns − 1) = 2 × 3."),
            q("A cell's expected count is…",
              ["Row total × column total ÷ grand total", "Grand total ÷ number of cells", "Observed count ÷ 2", "Row total − column total"], 0,
              "What you'd expect if the variables were independent."),
            q("Cramér's V ranges from…",
              ["−1 to 1", "0 to 1", "0 to ∞", "1 to 10"], 1,
              "0 = no association, 1 = perfect association."),
        ],
        "non-parametric": [
            q("Kruskal–Wallis is the rank-based alternative to…",
              ["A paired t-test", "One-way ANOVA", "Correlation", "Chi-square"], 1,
              "It compares 3+ independent groups using ranks."),
            q("Spearman's ρ is Pearson's r computed on…",
              ["Logged values", "Ranks", "z-scores", "Medians"], 1,
              "That's why it captures any monotonic relationship."),
            q("Rank tests are most useful for…",
              ["Large normal samples", "Single ordinal items or small, heavily skewed samples", "Binary outcomes", "Time series"], 1,
              "They don't assume interval-level, normal data."),
        ],
        "correlation": [
            q("r = −.45 describes…",
              ["A weak positive relationship", "A moderate negative relationship", "No relationship", "A perfect relationship"], 1,
              "The sign is direction; the size is strength."),
            q("If r = .30, what share of variance is shared?",
              ["9%", "30%", "60%", "3%"], 0,
              "r² = .09."),
            q("Studying only high scorers on X (restricted range) tends to…",
              ["Strengthen the correlation", "Weaken the correlation", "Leave it unchanged", "Reverse its sign"], 1,
              "Less variation in X leaves less covariation to detect."),
        ],
        "simple-regression": [
            q("Intercept = 2.0, slope = 0.5. What is the predicted y at x = 4?",
              ["2.5", "4.0", "4.5", "6.0"], 1,
              "2.0 + 0.5 × 4 = 4.0."),
            q("A residual is…",
              ["Observed − predicted", "Predicted − mean", "The slope", "The standard error"], 0,
              "What the model fails to explain for one observation."),
            q("A funnel shape in the residual-vs-fitted plot indicates…",
              ["Non-normal predictors", "Unequal variance (heteroscedasticity)", "Perfect fit", "Multicollinearity"], 1,
              "Use robust standard errors or transform the outcome."),
        ],
        "multiple-regression": [
            q("The coefficient for `gender[T.woman]` is 0.30. This means women score…",
              ["0.30 higher than the reference group, holding other predictors constant", "30% higher", "0.30 SD higher", "0.30 lower"], 0,
              "Dummy coefficients compare each level to the reference."),
            q("A categorical predictor with 5 levels becomes how many dummy variables?",
              ["1", "4", "5", "10"], 1,
              "k − 1."),
            q("The main problem with stepwise selection is that it…",
              ["Is slow", "Capitalizes on chance, giving overfitted models and biased p-values", "Can't handle dummies", "Requires centering"], 1,
              "Selected models rarely replicate."),
        ],
        "logistic-regression": [
            q("A log-odds of 0 corresponds to a probability of…",
              [".00", ".25", ".50", "1.00"], 2,
              "Even odds."),
            q("An odds ratio of 0.5 means the odds are…",
              ["Doubled", "Halved", "Unchanged", "Reduced by 5%"], 1,
              "OR < 1 means lower odds."),
            q("Convert a predicted log-odds of 1.1 to a probability.",
              ["≈ .25", "≈ .50", "≈ .75", "≈ .99"], 2,
              "1 / (1 + e^−1.1) ≈ .75."),
        ],
        "mixed-models": [
            q("A random intercept for participants accounts for…",
              ["Participants' different baseline levels", "Different slopes for conditions", "Measurement error in items", "Missing data"], 0,
              "Each participant gets their own intercept."),
            q("The ICC from a random-intercept model is…",
              ["The share of variance between groups", "A p-value", "The slope", "The number of groups"], 0,
              "High ICC = observations within a group are similar."),
            q("lme4 warns “boundary (singular) fit”. Usually this means…",
              ["The model is perfect", "A random-effect variance is estimated at (or near) zero", "The data are missing", "You need more fixed effects"], 1,
              "Consider simplifying the random-effects structure."),
        ],
        "reliability": [
            q("Holding inter-item correlations constant, adding more items makes α…",
              ["Lower", "Higher", "Unchanged", "Negative"], 1,
              "α depends on both the number of items and their average correlation."),
            q("Why is McDonald's ω often preferred to α?",
              ["It's always higher", "It doesn't assume every item loads equally", "It needs fewer participants", "It works only for binary items"], 1,
              "α assumes tau-equivalence; ω relaxes that."),
            q("EFA differs from CFA in that EFA…",
              ["Tests a specified structure", "Explores the structure without specifying it in advance", "Requires lavaan", "Can't estimate loadings"], 1,
              "CFA tests a hypothesized structure."),
        ],
        "reporting": [
            q("HARKing stands for…",
              ["Hypothesizing After the Results are Known", "Hierarchical Analysis of Regression Kinds", "High Alpha Reliability Keying", "A replication method"], 0,
              "Presenting post-hoc hypotheses as if they were planned."),
            q("In a registered report, peer review happens…",
              ["After publication", "Before results exist", "Only for replications", "Never"], 1,
              "Acceptance doesn't depend on whether results are significant."),
            q("Which belongs in a transparent methods section?",
              ["Every exclusion and the reason for it", "Only significant results", "Only the final model", "Nothing about software"], 0,
              "Readers need to know what was done to the data."),
        ],
    ]

    // MARK: Units 7–9

    private static let extraQuestionsResearch: [String: [Question]] = [
        "scale-scoring": [
            q("A prorating rule of “at least 80% of items” on a 10-item scale requires…",
              ["5 items", "8 items", "9 items", "10 items"], 1,
              "80% of 10 = 8."),
            q("On a 1–5 scale, a reverse-keyed response of 4 becomes…",
              ["1", "2", "3", "4"], 1,
              "6 − 4 = 2."),
            q("Two scales have reliabilities of .80 and .85. Their product term's reliability is roughly…",
              [".95", ".83", ".68", ".40"], 2,
              "Approximately the product, .80 × .85 ≈ .68, when the scales are uncorrelated."),
        ],
        "comparing-predictors": [
            q("A VIF of 1 means…",
              ["Perfect collinearity", "No collinearity with the other predictors", "The predictor is significant", "β = 1"], 1,
              "VIF = 1 / (1 − R²) from regressing the predictor on the others."),
            q("A standardized β of .30 means…",
              ["A 30% increase", "A 0.30 SD change in the outcome per SD of the predictor", "r = .30 always", "p = .30"], 1,
              "βs are in SD units."),
            q("Why must nested models be compared on the same rows?",
              ["To save time", "Otherwise ΔR² mixes differences in predictors with differences in sample", "Software requires it", "It raises R²"], 1,
              "Drop incomplete cases before fitting all models."),
        ],
        "moderation": [
            q("b_X = 0.5, b_X×W = −0.2, and W is centered with SD = 1. What is the simple slope of X at +1 SD of W?",
              ["0.7", "0.5", "0.3", "−0.2"], 2,
              "0.5 + (−0.2 × 1) = 0.3."),
            q("A Johnson–Neyman interval tells you…",
              ["Where the moderator is normally distributed", "The values of W for which the X slope is significant", "The best number of classes", "The model's R²"], 1,
              "It maps significance across the whole moderator range."),
            q("In an *uncentered* interaction model, the coefficient on X is…",
              ["The average effect of X", "The effect of X when W = 0", "The interaction", "Meaningless always"], 1,
              "That's why centering makes it interpretable."),
        ],
        "mediation": [
            q("Total effect c = 0.50 and direct effect c′ = 0.30. The indirect effect is…",
              ["0.80", "0.20", "0.15", "0.60"], 1,
              "c = c′ + ab, so ab = 0.20."),
            q("Using the numbers above, the proportion mediated is…",
              [".20", ".40", ".60", ".80"], 1,
              "0.20 / 0.50 = .40 — but it's unstable when c is small."),
            q("The bootstrap 95% CI for an indirect effect is [0.02, 0.15]. You conclude…",
              ["No mediation", "The indirect effect is supported", "Full mediation", "The model is wrong"], 1,
              "The CI excludes 0."),
        ],
        "moderated-mediation": [
            q("The index of moderated mediation is −0.08. This means…",
              ["The indirect effect decreases by 0.08 per unit increase in W", "The direct effect is −0.08", "W has no effect", "The model failed"], 0,
              "It's the slope of the indirect effect on W."),
            q("PROCESS Model 7 and Model 14 differ in…",
              ["Which path W moderates: Model 7 the a path, Model 14 the b path", "The number of mediators", "Whether they bootstrap", "Nothing"], 0,
              "First-stage vs. second-stage moderation."),
            q("Conditional indirect effects: significant at low W, non-significant at high W. Can you claim moderated mediation?",
              ["Yes, always", "Only if the index of moderated mediation's CI excludes 0", "No, never", "Only with p < .01"], 1,
              "A difference in significance isn't a significant difference."),
        ],
        "ordinal-models": [
            q("An ordinal outcome with 7 categories has how many thresholds?",
              ["5", "6", "7", "8"], 1,
              "k − 1 cut points."),
            q("In a cumulative logit model, OR = 0.4 for `complex` means complex sentences have…",
              ["Higher odds of a higher rating", "Lower odds of being in a higher rating category", "Ratings exactly 40% lower", "No effect"], 1,
              "OR < 1 shifts responses toward lower categories."),
            q("Violating the proportional-odds assumption means…",
              ["The predictor's effect differs across thresholds", "The data are continuous", "There are too many categories", "Random effects are needed"], 0,
              "Consider partial proportional-odds models."),
        ],
        "mixed-logistic": [
            q("Testing whether a logistic intercept differs from 0 tests whether…",
              ["The outcome is always 1", "The probability differs from .50 (when predictors are 0)", "There are random effects", "The slope is 0"], 1,
              "Logit 0 = probability .50."),
            q("Why not fit a plain logistic regression to repeated trials from the same participants?",
              ["It can't use binary outcomes", "It treats clustered trials as independent, inflating significance", "It's slower", "It needs ordinal data"], 1,
              "Clustering must be modeled (random effects or GEE)."),
            q("For logistic models, mixed-model (conditional) effects compared with GEE (marginal) effects are usually…",
              ["Identical", "Somewhat larger in magnitude", "Always smaller", "Opposite in sign"], 1,
              "Conditional effects describe a typical participant and item and are typically farther from 0."),
        ],
    ]

    // MARK: Unit 10

    private static let extraQuestionsStructure: [String: [Question]] = [
        "bootstrap": [
            q("What does the SD of a bootstrap distribution estimate?",
              ["The population SD", "The standard error of the statistic", "The p-value", "The sample size"], 1,
              "The spread of the statistic across resamples approximates its sampling variability."),
            q("Why can a naive CI be too narrow for diary data?",
              ["Diaries are biased", "Days from the same person aren't independent, so the effective sample size is smaller", "Bootstraps are always wider", "There are too many days"], 1,
              "Clustering reduces the information in the data."),
            q("Which question does a permutation test answer?",
              ["How precise is my estimate?", "How surprising is my result if group labels didn't matter?", "How many resamples do I need?", "Is the sample representative?"], 1,
              "Permutation tests build the null distribution; bootstraps build confidence intervals."),
        ],
        "sample-planning": [
            q("If the true effect size doubles, the required sample size roughly…",
              ["Doubles", "Halves", "Quarters", "Stays the same"], 2,
              "n scales with 1 / effect²."),
            q("ΔR² = .02 for a term, and the full model has R² = .20. What is f²?",
              [".02", ".025", ".10", ".20"], 1,
              ".02 / (1 − .20) = .025."),
            q("An interim look after 120 of a planned 300 participants has an information fraction of…",
              [".4", ".6", ".12", "2.5"], 0,
              "120 / 300 = .4."),
        ],
        "ancova": [
            q("An intention-to-treat analysis…",
              ["Analyzes everyone as randomized, regardless of compliance", "Drops non-compliers", "Uses only the control group", "Is a one-tailed test"], 0,
              "It preserves the benefits of randomization."),
            q("Two-tailed p = .08, and the effect is in the preregistered direction. The one-tailed p is…",
              [".16", ".08", ".04", ".02"], 2,
              "Halve the two-tailed p when the effect is in the predicted direction."),
            q("How do you check the homogeneity-of-slopes assumption?",
              ["Compare group means", "Test a group × covariate interaction", "Run a chi-square test", "Look at the intercept"], 1,
              "If the covariate's slope differs a lot between groups, a single adjusted difference is misleading."),
        ],
        "between-within": [
            q("Between-person r = +.6, within-person r = −.4. A pooled correlation of all rows will most likely be…",
              ["Exactly −.4", "Exactly +.6", "Somewhere between, misrepresenting both", "Always 0"], 2,
              "The pooled correlation blends the two components."),
            q("In a multilevel model, `hours_within` (person-mean centered) and `hours_between` (person mean) are both included. What does the coefficient on `hours_within` estimate?",
              ["The difference between people", "The effect of working more than one's own usual amount", "The average wellbeing", "The ICC"], 1,
              "Within-person effects compare a person with themselves."),
            q("A cross-level interaction tests whether…",
              ["Two people differ", "A person-level variable changes a within-person relationship", "Days are independent", "The intercept is zero"], 1,
              "E.g. whether conscientiousness changes how strongly daily work hours relate to wellbeing."),
        ],
        "inter-rater": [
            q("Cohen's κ = 0 means…",
              ["No agreement at all", "Agreement equal to chance", "Perfect agreement", "Raters disagreed on everything"], 1,
              "κ measures agreement beyond chance."),
            q("Krippendorff's α = .72 meets which common standard?",
              ["Reliable (≥ .80)", "Tentative conclusions only (≥ .667)", "Unacceptable", "Perfect"], 1,
              "Many fields require ≥ .80 for firm conclusions."),
            q("Raters should ideally be blind to…",
              ["The scoring guide", "Hypotheses and anything about the cases that could bias their judgments", "Each other's names", "The cases"], 1,
              "Blinding prevents expectations from shaping scores."),
        ],
        "multinomial": [
            q("A multinomial model of commute mode uses car as the reference. The bike coefficient for `week` is +0.15. This means…",
              ["Biking falls over time", "Each week, the odds of biking rather than driving rise by about 16%", "15% of people bike", "Week doesn't matter"], 1,
              "exp(0.15) ≈ 1.16."),
            q("The diagonal of a transition matrix shows…",
              ["The overall share of each category", "How often people repeat the same category at the next occasion", "The reference category", "Missing data"], 1,
              "High diagonal values mean choices are sticky."),
            q("Your categories are “strongly disagree” to “strongly agree”. Should you use a multinomial model?",
              ["Yes, always", "No — they're ordered, so an ordinal model fits better", "Only with random effects", "Only for two categories"], 1,
              "Multinomial models ignore order."),
        ],
        "latent-class": [
            q("LCA indicators should be…",
              ["Continuous and normally distributed", "Categorical and roughly independent within classes", "Perfectly correlated", "Ratings from one item"], 1,
              "That's the local independence assumption."),
            q("A 4-class solution has one class holding 2% of the sample. Typically you…",
              ["Keep it — small classes are important", "Prefer a solution without such a tiny class unless it's clearly meaningful", "Double the sample", "Ignore BIC"], 1,
              "Tiny classes are often unstable artifacts."),
            q("“Label switching” means…",
              ["Class numbers can change between runs while the solution is the same", "Indicators swap meaning", "Raters disagree", "Entropy flips"], 0,
              "Always identify classes by their profiles."),
        ],
        "latent-profile": [
            q("Why plot standardized (z-scored) profile means?",
              ["To make BIC lower", "So indicators on different scales can be compared on one axis", "Mplus requires it", "To remove outliers"], 1,
              "Raw means on different scales are hard to compare."),
            q("BIC is lowest at 3 profiles, with sizes 50%, 30%, and 20%, and each profile is interpretable. You'd choose…",
              ["2", "3", "4", "6"], 1,
              "Lowest BIC, no tiny classes, and interpretable."),
            q("In sklearn, `covariance_type=\"full\"` allows…",
              ["Only equal variances", "Indicators to covary within profiles", "No variances", "Categorical indicators"], 1,
              "It frees the whole covariance matrix in each profile."),
        ],
        "mplus-mixtures": [
            q("aBIC is…",
              ["Absolute BIC", "Sample-size-adjusted BIC", "Average BIC across starts", "A bootstrap test"], 1,
              "Like BIC, lower is better."),
            q("What is `AUXILIARY = age (R3STEP);` for?",
              ["Comparing age means across classes", "Testing whether age predicts class membership", "Treating age as an indicator", "Removing age"], 1,
              "R3STEP runs a three-step multinomial regression of membership on covariates."),
            q("What does `LRTSTARTS` control?",
              ["Random starts for the bootstrapped LRT (TECH14)", "The number of classes", "Missing-data handling", "Output format"], 0,
              "The bootstrap re-estimates K and K − 1 class models many times."),
        ],
        "clustering": [
            q("What is the cosine similarity of a normalized embedding with itself?",
              ["0", "0.5", "1", "−1"], 2,
              "Same direction."),
            q("k-means requires you to…",
              ["Choose the number of clusters in advance", "Label noise points", "Use categorical data", "Run Mplus"], 0,
              "That's why you compare silhouettes across k."),
            q("How does a medoid differ from a centroid?",
              ["It's always larger", "It's an actual observation rather than an average point", "It's the cluster's most distant member", "There's no difference"], 1,
              "Medoids give real prototypes."),
        ],
        "keyness": [
            q("A word has weighted log-odds z = 2.5 for group A vs. B. It is…",
              ["Distinctive of group B", "Distinctive of group A", "Equally common", "A stop word"], 1,
              "Positive z favors the first group."),
            q("Strengthening the Dirichlet prior makes estimates…",
              ["More extreme", "Shrink more toward the background rate", "Ignore rare words entirely", "Unchanged"], 1,
              "More evidence is needed to stand out."),
            q("Why not rank words by raw frequency difference?",
              ["It's too slow", "It ignores corpus sizes and overstates rare-word differences", "It needs a prior", "It requires embeddings"], 1,
              "Normalization and shrinkage address both problems."),
        ],
    ]

    // MARK: Units 11–12

    private static let extraQuestionsVisualsAndLabs: [String: [Question]] = [
        "plotting-basics": [
            q("seaborn is built on top of…",
              ["ggplot2", "matplotlib", "pandas only", "Excel"], 1,
              "seaborn produces matplotlib figures and axes."),
            q("`facet_wrap(~ source)` creates…",
              ["A color legend", "One panel per value of source", "A regression line", "A heatmap"], 1,
              "Small multiples."),
            q("Which palette type suits a magnitude such as a count?",
              ["Categorical", "Sequential (one hue, light → dark)", "Diverging", "Rainbow"], 1,
              "Magnitudes have an order but no meaningful midpoint."),
        ],
        "plotting-groups": [
            q("Compared with SE bars, 95% CI bars are…",
              ["Narrower", "About twice as wide", "Identical", "Only for medians"], 1,
              "A 95% CI is roughly mean ± 2 SE."),
            q("Connecting each participant's pre and post score with a line shows…",
              ["Only the group mean", "Individual change", "The distribution of the control group", "Nothing useful"], 1,
              "Readers see how consistent the change is."),
            q("Why jitter points in a strip plot?",
              ["To add noise to the analysis", "To reduce overplotting of identical values", "To change the mean", "To hide outliers"], 1,
              "It's a display choice only."),
        ],
        "plotting-relationships": [
            q("`geom_smooth(method = \"lm\")` draws…",
              ["A loess curve", "A fitted regression line with its CI band", "Raw points", "A histogram"], 1,
              "Without `method = \"lm\"`, ggplot defaults to a smoother."),
            q("Thousands of points overlap in a scatterplot. A good fix is…",
              ["A pie chart", "Transparency (alpha), jitter, or a 2-D density/hexbin plot", "Removing data", "A 3-D plot"], 1,
              "These reveal where points concentrate."),
            q("Where should the neutral color sit on a correlation heatmap's scale?",
              ["At −1", "At 0", "At 1", "At the mean correlation"], 1,
              "Zero is the meaningful midpoint."),
        ],
        "plotting-models": [
            q("In a coefficient plot of odds ratios, the reference line goes at…",
              ["0", "1", "0.5", "The mean OR"], 1,
              "OR = 1 means no effect."),
            q("Why plot odds ratios on a log scale?",
              ["To hide large ORs", "So that, e.g., OR = 2 and OR = 0.5 are equally far from 1", "Software requires it", "To make CIs narrower"], 1,
              "Log scale makes multiplicative effects symmetric."),
            q("For stacked bars of 1–7 agreement ratings with a neutral midpoint, the best colors are…",
              ["Random", "Two hues diverging from a neutral gray at the midpoint", "One hue light → dark", "All black"], 1,
              "Disagree and agree are opposite directions around a neutral center."),
        ],
        "publication-figures": [
            q("Which export format stays sharp at any zoom?",
              ["JPEG", "PNG at 72 dpi", "Vector PDF or SVG", "GIF"], 2,
              "Vectors store shapes, not pixels."),
            q("Why shouldn't color be the only cue in a legend?",
              ["It takes too long", "Colorblind and grayscale readers can't distinguish the series", "Journals ban color", "It's slower to render"], 1,
              "Add direct labels, shapes, or line styles."),
            q("What's a common minimum resolution for raster figures in journals?",
              ["72 dpi", "150 dpi", "300 dpi", "30 dpi"], 2,
              "Many journals require 300 dpi or higher."),
        ],
        "lab-hsb2": [
            q("hsb2 test scores are standardized. Their means are near…",
              ["0", "50", "100", "5"], 1,
              "They're T-score-like, centered near 50 with SD about 10."),
            q("To compare math scores across three program types, the appropriate first test is…",
              ["A t-test", "One-way ANOVA", "Chi-square", "Logistic regression"], 1,
              "Follow up with corrected post-hoc tests."),
            q("SES (3 levels) × school type (2 levels) is analyzed with a chi-square test with how many df?",
              ["1", "2", "3", "6"], 1,
              "(3 − 1) × (2 − 1) = 2."),
        ],
        "lab-resume": [
            q("Why is the race effect in the résumé study interpretable as causal?",
              ["The sample is large", "Names were randomly assigned to résumés", "It used logistic regression", "p < .001"], 1,
              "Random assignment rules out confounds on average."),
            q("Callback rates are 9.7% vs. 6.4%. The difference in percentage points is about…",
              ["3.3", "1.5", "51", "16"], 0,
              "9.7 − 6.4 ≈ 3.3 points (about 50% higher relative rate)."),
            q("Which model handles the binary callback outcome with several predictors?",
              ["Linear regression", "Logistic regression", "ANOVA", "Paired t-test"], 1,
              "Binary outcome → logistic."),
        ],
        "lab-evals": [
            q("Why add a random intercept for `prof_id` in the evaluations data?",
              ["Professors teach several courses, so rows are clustered", "To increase R²", "Because scores are ordinal", "It's required for interactions"], 0,
              "Otherwise standard errors are too small."),
            q("r = .19 between appearance and score means appearance explains about how much variance?",
              ["19%", "3.6%", "38%", "1.9%"], 1,
              ".19² ≈ .036."),
            q("To get the appearance slope for male professors directly, you…",
              ["Drop female professors", "Make male the reference level", "Center the outcome", "Use a log scale"], 1,
              "The main effect becomes the slope for the reference group."),
        ],
        "which-test": [
            q("Students answer eight yes/no questions about their study habits, and you want to discover recurring types. Method?",
              ["Latent class analysis", "Latent profile analysis", "ANCOVA", "Pearson correlation"], 0,
              "Categorical indicators → LCA."),
            q("You have four continuous wellbeing scores per person and want to find subgroups. Method?",
              ["Latent class analysis", "Latent profile analysis", "Chi-square", "Keyness"], 1,
              "Continuous indicators → LPA."),
            q("Participants rate sentences on a 1–7 scale; each participant rates many sentences and each sentence is rated by many participants. Model?",
              ["Linear regression", "Ordinal mixed model with crossed random effects", "Chi-square", "t-test"], 1,
              "Ordered outcome with participants and items crossed."),
            q("You want to know which words distinguish two groups' essays. Method?",
              ["Weighted log-odds keyness", "ANOVA", "Mediation", "LPA"], 0,
              "Keyness compares word frequencies across corpora."),
            q("People choose among four transport modes every week for ten weeks. Inferential model?",
              ["Ordinal model", "Multinomial mixed model with a random intercept for person", "Paired t-test", "Linear regression"], 1,
              "Unordered categories, repeated within people."),
            q("A diary study asks whether stress is higher on days with less sleep than usual. Which predictor do you need?",
              ["Each person's average sleep", "Sleep person-mean centered (each day's deviation from the person's average)", "Total sleep across the study", "Sleep z-scored across all rows"], 1,
              "“Than usual” is a within-person question."),
        ],
    ]
}
