#!/usr/bin/env python3
"""Rebuild the practice datasets bundled with the app (akstats/PracticeData).

Runs the Python generator scripts in scripts/python, copies their CSVs into akstats/PracticeData, builds
practice_data.xlsx (one sheet per dataset), and writes the folder's README with a description of each file.

    python3 tools/build_practice_data.py           # rebuild everything (needs numpy, pandas, openpyxl)
    python3 tools/build_practice_data.py --check   # regenerate and compare with the bundled CSVs (used by CI)
"""
import csv
import filecmp
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "akstats" / "PracticeData"
GENERATORS = ["generate_data", "generate_more_data", "generate_extra_data", "generate_simulations"]
GROUPS = [
    ("Course datasets", "Simulated datasets used by lessons from Unit 3 onward, each with built-in effects.",
     ["survey", "diary", "classroom", "essays", "stroop", "stroop_trials", "judgments", "commutes", "habits",
      "profiles", "missing", "fillers", "poll", "tutoring", "growth"]),
    ("Practice simulation: political parasocial attachment",
     "A survey with a credibility judgment task, coded interviews, and a randomized intervention.",
     ["ppsr_survey", "credibility_trials", "ppsr_narratives", "ppsr_experiment"]),
    ("Practice simulation: asking chatbots about court cases",
     "Session transcripts, exported chat logs, the speech-act coding sheet and both coders' sheets, the interview framework matrix, and coded chatbot responses.",
     ["llm_sessions", "llm_transcripts", "llm_chat_export", "llm_coding", "llm_coder_a", "llm_coder_b",
      "llm_card_labels", "llm_instrument_coding", "llm_framework", "llm_indexing", "llm_responses"]),
]
NAMES = [name for _, _, names in GROUPS for name in names]


def generate(folder: pathlib.Path) -> None:
    for script in GENERATORS:
        subprocess.run([sys.executable, str(ROOT / "scripts" / "python" / f"{script}.py")], cwd=folder, check=True,
                       stdout=subprocess.DEVNULL)


def descriptions() -> dict:
    """Each file's description, from the key terms of the app's Practice datasets lesson."""
    swift = (ROOT / "akstats" / "CurriculumCoding.swift").read_text(encoding="utf-8")
    terms = re.findall(r'Term\("([^"]+\.csv[^"]*)", "((?:[^"\\]|\\.)*)"\)', swift)
    out = {}
    for name in NAMES:
        for term, text in terms:
            if f"{name}.csv" in re.split(r"[ /,]+", term):
                out[name] = text.replace('\\"', '"')
                break
        else:
            raise SystemExit(f"no description for {name}.csv in CurriculumCoding.swift")
    return out


def write_readme(about: dict) -> None:
    lines = ["# Practice data", "",
             "Every dataset used by the course's exercises — the same files the app's **Practice data** view offers for download.",
             "They are made by the scripts in [`scripts/`](../../scripts) with fixed random seeds (these are the Python versions;",
             "the R scripts make files with the same structure but different random numbers). Click a file to preview it as a table,",
             "or open [`practice_data.xlsx`](practice_data.xlsx) for all of them in one workbook. All people, figures, and chatbots are simulated.", ""]
    for title, summary, names in GROUPS:
        lines += [f"## {title}", "", summary, "", "| File | Rows | Columns | What's in it |", "|---|---|---|---|"]
        for name in names:
            with open(DATA / f"{name}.csv", encoding="utf-8", newline="") as f:
                rows = list(csv.reader(f))
            text = about[name].replace("|", "\\|")
            lines.append(f"| [`{name}.csv`]({name}.csv) | {len(rows) - 1:,} | {len(rows[0])} | {text} |")
        lines.append("")
    lines += ["To rebuild these files after changing a generator, run `python3 tools/export_scripts.py` and then",
              "`python3 tools/build_practice_data.py` from the repository root.", ""]
    (DATA / "README.md").write_text("\n".join(lines), encoding="utf-8")


def write_workbook(about: dict) -> None:
    import openpyxl
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    bold, fill = Font(bold=True), PatternFill("solid", fgColor="DCE6F1")
    wb = openpyxl.Workbook()
    readme = wb.active
    readme.title = "Read me"
    readme.append(["Practice data — every dataset used in the course's exercises. Generated by the course's Python scripts "
                   "(the R scripts make data with the same structure but different random numbers)."])
    readme.append([])
    readme.append(["Sheet / file", "Group", "Rows", "Columns", "What's in it"])
    for cell in readme[3]:
        cell.font, cell.fill = bold, fill
    for title, _, names in GROUPS:
        for name in names:
            with open(DATA / f"{name}.csv", encoding="utf-8", newline="") as f:
                rows = list(csv.reader(f))
            readme.append([name, title, len(rows) - 1, len(rows[0]), re.sub(r"[`*]", "", about[name])])
            ws = wb.create_sheet(name[:31])
            for i, row in enumerate(rows):
                values = []
                for v in row:
                    if i and re.fullmatch(r"-?\d+", v) and len(v) < 15:
                        values.append(int(v))
                    elif i and re.fullmatch(r"-?\d*\.\d+(e-?\d+)?", v):
                        values.append(float(v))
                    else:
                        values.append(v)
                ws.append(values)
            for cell in ws[1]:
                cell.font, cell.fill = bold, fill
            ws.freeze_panes, ws.auto_filter.ref = "A2", ws.dimensions
            for j, column in enumerate(rows[0], start=1):
                width = max([len(column)] + [len(r[j - 1]) for r in rows[1:200] if len(r) >= j])
                ws.column_dimensions[get_column_letter(j)].width = min(60, width + 2)
    for column, width in zip("ABCDE", (24, 46, 8, 8, 120)):
        readme.column_dimensions[column].width = width
    for row in readme.iter_rows(min_row=4):
        row[4].alignment = Alignment(wrap_text=True, vertical="top")
    levels = {  # the coding sheet's dropdown levels, as on the team's template
        "clause_type": ["Declarative", "Interrogative (polar)", "Interrogative (wh)", "Imperative", "Fragment"],
        "primary_act": ["Summary", "Explanation", "Evaluation of fairness", "Opinion", "Prediction", "Personal advice",
                        "Verification", "Clarification", "Pushback", "Meta"],
        "directness": ["Direct", "Indirect"], "Y/N": ["Y", "N"],
        "trigger_type": ["Factive verb", "Evaluative description", "Change of state", "Why question", "Multiple (list in Notes)"],
        "presup_direction": ["Left", "Right", "Neutral", "Unclear"], "leading_construction": ["None", "Tag question", "Negative polar"],
        "polarity": ["Positive", "Negative", "Mixed"],
        "target": ["Policy", "Party/politician", "Group", "LLM", "Issue/situation", "Media", "Other"],
        "disclosure_direction": ["Left", "Right", "Unclear"], "relation": ["New", "Continuation", "Uptake"], "confidence": [1, 2, 3]}
    lists = wb.create_sheet("Coding lists")
    lists.append(list(levels))
    for cell in lists[1]:
        cell.font, cell.fill = bold, fill
    for i in range(max(map(len, levels.values()))):
        lists.append([v[i] if i < len(v) else None for v in levels.values()])
    for j in range(1, len(levels) + 1):
        lists.column_dimensions[get_column_letter(j)].width = 24
    wb.save(DATA / "practice_data.xlsx")


def main() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        generate(tmp)
        if "--check" in sys.argv:
            differs = [n for n in NAMES if not filecmp.cmp(tmp / f"{n}.csv", DATA / f"{n}.csv", shallow=False)]
            if differs:
                sys.exit("bundled data differ from what the scripts generate: " + ", ".join(f"{n}.csv" for n in differs))
            print(f"all {len(NAMES)} bundled CSVs match the scripts")
            return
        DATA.mkdir(parents=True, exist_ok=True)
        for name in NAMES:
            shutil.copy(tmp / f"{name}.csv", DATA / f"{name}.csv")
    about = descriptions()
    write_readme(about)
    write_workbook(about)
    print(f"rebuilt {len(NAMES)} CSVs, practice_data.xlsx, and README.md in {DATA.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
